# -*- coding: windows-1250 -*-
# saved: 2020/11/02 21:15:56

import CLASSES_Library_NetBase_Utils_XMLUtil as XMLUtil

import random
import calendar

imiona=[
   'Adam', 'Adrian', 'Albert', 'Aleksander', 'Aleksy', 
   'Alfred', 'Andrzej', 'Antoni', 'Arek', 'Arkadiusz', 
   'Arnold', 'Artur', 'Bartek', 'Bartosz', 'Bartłomiej', 
   'Benedykt', 'Bernard', 'Bogdan', 'Bogumił', 'Bogusław', 
   'Bohdan', 'Borys', 'Bruno', 'Błażej', 'Cezary', 
   'Czarek', 'Czesław', 'Damian', 'Daniel', 'Darek',
   'Dariusz', 'Dawid', 'Doman', 
   'Dominik', 'Edmund', 'Edward', 'Emil', 
   'Ernest', 'Eryk', 'Eugeniusz', 'Filip', 'Franciszek', 
   'Fryderyk', 'Gabriel',
   'Grzegorz', 'Grzesiek', 'Gwidon', 'Henryk', 
   'Hubert', 'Igor', 'Irek', 'Ireneusz', 'Jacek', 
   'Jakub', 'Jan', 'Janusz', 'Jarek', 'Jarosław', 
   'Jeremi', 'Jerzy', 'Joachim', 'Juliusz', 'Jurek', 
   'Józef', 'Kacper', 'Kamil', 
   'Karol', 'Konrad', 'Kornel', 
   'Krystian', 'Krzysiek', 'Krzysztof', 'Lech', 'Leon', 
   'Lesław', 'Leszek', 'Ludwik', 'Maciej',
   'Maciek', 'Maksymilian', 'Marcel', 'Marcin', 'Marek', 
   'Marian', 'Mariusz', 'Mateusz', 'Maurycy', 'Michał', 
   'Mieczysław', 'Mieszko', 'Mikołaj', 'Miłosz', 'Mirek',
   'Miron', 'Mirosław', 'Norbert', 'Olaf', 'Olek',
   'Olgierd', 'Oskar', 'Patryk', 'Paweł', 'Piotr',
   'Przemek', 'Przemysław', 'Radek', 'Radomir',
   'Radosław', 'Rafał', 'Rajmund', 'Robert', 'Roch',
   'Roman', 'Romek', 'Romuald', 'Ryszard', 'Sebastian', 
   'Sergiusz', 'Seweryn', 'Sławek', 'Sławomir', 'Stanisław',
   'Stefan', 'Sylwester', 'Szymon', 'Tadeusz', 
   'Tomasz', 'Tomek', 'Wacław', 'Waldemar', 
   'Wiesław', 'Wiktor', 'Witold',
   'Wojciech', 'Wojtek', 'Władysław', 'Włodek', 'Włodzimierz', 
   'Zbigniew', 'Zbyszek', 'Zdzisław', 'Zenon', 'Ziemek', 
   'Ziemowit', 'Zygmunt', 'Łukasz', 
   ]

imionameskie= [
   'Aaron', 'Abdiasz', 'Abel', 'Abraham', 'Adam', 
   'Adolf', 'Adrian', 'Agenor', 'Albert', 'Albrecht', 
   'Albin', 'Aleksander', 'Aleksy', 'Alfons', 'Alfred', 
   'Alojzy', 'Amadeusz', 'Ambroży', 'Amos', 'Anastazy', 
   'Anatol', 'Andrzej', 'Antoni', 'Anzelm', 'Apolinary', 
   'Apoloniusz', 'Arkadiusz', 'Arnold', 'Aron', 'Artur', 
   'Atanazy', 'August', 'Augustyn', 'Aureli', 'Aurelian', 
   'Aureliusz', 'Axel', 'Barnaba', 'Barnabasz', 'Bartłomiej', 
   'Bartosz', 'Bazyli', 'Benedykt', 'Beniamin', 'Benon', 
   'Bernard', 'Bernardyn', 'Bertold', 'Błażej', 'Bogdan', 
   'Bogusław', 'Bogusz', 'Bohdan', 'Bolesław', 'Bonawentura', 
   'Bonifacy', 'Borys', 'Borysław', 'Borzysław', 'Bożydar', 
   'Bronimir', 'Bronisław', 'Brunon', 'Cecylian', 'Celestyn', 
   'Cezariusz', 'Cezary', 'Cyprian', 'Cyriak', 'Cyryl', 
   'Czesław', 'Damazy', 'Damian', 'Daniel', 'Dariusz', 
   'Dawid', 'Dezydery', 'Dezyderiusz', 'Dionizy', 'Dobiesław', 
   'Dobromir', 'Dobromierz', 'Dobrosław', 'Domicjan', 'Dominik', 
   'Domosław', 'Donald', 'Donat', 'Dorian', 'Duszan', 
   'Dymitr', 'Dyzma', 'Edgar', 'Edmund', 'Edward', 
   'Edwin', 'Egbert', 'Egon', 'Eliasz', 'Eligiusz', 
   'Elizeusz', 'Emanuel', 'Emil', 'Emilian', 'Erazm', 
   'Ernest', 'Eryk', 'Erwin', 'Eugeniusz', 'Eustachy', 
   'Euzebiusz', 'Ewald', 'Ewaryst', 'Ezdrasz', 'Ezechiel', 
   'Fabian', 'Faustyn', 'Felicjan', 'Feliks', 'Ferdynand', 
   'Fidelis', 'Filemon', 'Filip', 'Flawiusz', 'Florian', 
   'Fortunat', 'Franciszek', 'Fryderyk', 'Gabor', 'Gabriel', 
   'Gaweł', 'Gedeon', 'Gerwazy', 'Gilbert', 'Gniewomir', 
   'Goliat', 'Gościmił', 'Gościsław', 'Gotard', 'Gracjan', 
   'Grzegorz', 'Gustaw', 'Gwalbert', 'Gwidon', 'Heliodor', 
   'Helmut', 'Henryk', 'Herbert', 'Herman', 'Hieronim', 
   'Hilary', 'Hipolit', 'Honoriusz', 'Horacy', 'Hubert', 
   'Hugon', 'Idzi', 'Ignacy', 'Igor', 'Ildefons', 
   'Innocenty', 'Ireneusz', 'Irwin', 'Iwan', 'Iwo', 
   'Izydor', 'Izaak', 'Izajasz', 'Jacek', 'Jacenty', 
   'Jakub', 'Jan', 'Janisław', 'Janusz', 'Jaromir', 
   'Jarosław', 'Jeremi', 'Jeremiasz', 'Jerzy', 'Jędrzej', 
   'Joachim', 'Joel', 'Jonasz', 'Jonatan', 'Jordan', 
   'Jozue', 'Józef', 'Juda', 'Judasz', 'Julian', 
   'Juliusz', 'Jurand', 'Justyn', 'Kacper', 'Kain', 
   'Kajetan', 'Kalikst', 'Kamil', 'Kandyd', 'Karol', 
   'Kazimierz', 'Kiejstut', 'Klaudian', 'Klaudiusz', 'Klemens', 
   'Kleofas', 'Konrad', 'Konstancjusz', 'Konstanty', 'Konstantyn', 
   'Kornel', 'Korneliusz', 'Krzysztof', 'Kryspin', 'Krystyn', 
   'Ksawery', 'Kwiryn', 'Lambert', 'Laurenty', 'Lech', 
   'Leon', 'Leonard', 'Leonid', 'Leopold', 'Leszek', 
   'Longin', 'Lubomir', 'Lubor', 'Lubosław', 'Lucjan', 
   'Lucjusz', 'Ludomił', 'Ludomir', 'Ludosław', 'Ludwik', 
   'Lutomir', 'Ładysław', 'Łazarz', 'Łucjan', 'Łukasz', 
   'Maciej', 'Makary', 'Maksym', 'Maksymilian', 'Manfred', 
   'Mansfet', 'Marcel', 'Marceli', 'Marcelin', 'Marcin', 
   'Marcjal', 'Marcjan', 'Marek', 'Marian', 'Mariusz', 
   'Martynin', 'Mateusz', 'Medard', 'Melchior', 'Metody', 
   'Michał', 'Micheasz', 'Mieczysław', 'Mieszko', 'Mikołaj', 
   'Miłosz', 'Miromir', 'Miron', 'Mirosław', 'Mojżesz', 
   'Myślibor', 'Nahum', 'Namysław', 'Napoleon', 'Narcyz', 
   'Natan', 'Natanael', 'Nehemiasz', 'Nikodem', 'Noe', 
   'Norbert', 'Odon', 'Oktawian', 'Olaf', 'Olgierd', 
   'Onufry', 'Oswald', 'Otniel', 'Ozeasz', 'Pafnucy', 
   'Pankracy', 'Paschalis', 'Patrycjusz', 'Patrycy', 'Patryk', 
   'Paweł', 'Pelagiusz', 'Petroniusz', 'Piotr', 'Pius', 
   'Polikarp', 'Prokop', 'Prosper', 'Protazy', 'Przemysław', 
   'Przybysław', 'Racibor', 'Radek', 'Radomił', 'Radomir', 
   'Radosław', 'Radowit', 'Radzimierz', 'Radzimir', 'Rafał', 
   'Rajmund', 'Rajnold', 'Remigiusz', 'Robert', 'Roch', 
   'Rodryg', 'Roland', 'Roman', 'Romuald', 'Rościsław', 
   'Ruben', 'Rudolf', 'Rufin', 'Ryszard', 'Salomon', 
   'Samson', 'Samuel', 'Saturnin', 'Saul', 'Sebastian', 
   'Sergiusz', 'Serwacy', 'Seweryn', 'Sławoj', 'Sławomir', 
   'Sławosz', 'Sobiesław', 'Stanisław', 'Stefan', 'Sulimierz', 
   'Symeon', 'Sykstus', 'Sylweriusz', 'Sylwester', 'Sylwan', 
   'Sylwin', 'Sylwiusz', 'Szczepan', 'Szczęsny', 'Szymon', 
   'Ścibor', 'Tadeusz', 'Telesfor', 'Teobald', 'Teodor', 
   'Teodozjusz', 'Teofil', 'Tobiasz', 'Tomasz', 'Tomisław', 
   'Tymon', 'Tymoteusz', 'Tytus', 'Urban', 'Uriasz', 
   'Urlyk', 'Ursyn', 'Wacław', 'Waldemar', 'Walenty', 
   'Walerian', 'Walery', 'Walter', 'Wawrzyniec', 'Wespazjan', 
   'Wiaczesław', 'Wieńczysław', 'Wiesław', 'Wiktor', 'Wiktoryn', 
   'Wilhelm', 'Wincenty', 'Wirgiliusz', 'Wit', 'Witalis', 
   'Witold', 'Witomir', 'Witosław', 'Władysław', 'Włodzimierz', 
   'Wodzisław', 'Wojciech', 'Wszebor', 'Wyszomir', 'Zachariasz', 
   'Zbigniew', 'Zbisław', 'Zdobysław', 'Zdzisław', 'Zenobiusz', 
   'Zenon', 'Ziemowit', 'Zygfryd', 'Zygmunt', 'Żelisław', 
   'Żywisław'
   ]

imionazenskie= [
   'Abigail', 'Adela', 'Adelina', 'Adrianna', 'Agnieszka', 
   'Aida', 'Albina', 'Aldona', 'Aleksandra', 'Alfreda', 
   'Alicja', 'Alina', 'Alma', 'Amadea', 'Amalia', 
   'Amelia', 'Anastazja', 'Aneta', 'Angela', 'Angelina', 
   'Aniela', 'Anita', 'Anna', 'Antonina', 'Apolonia', 
   'Ariadna', 'Arlena', 'Asenat', 'Aurelia', 'Balbina', 'Barbara',
   'Batszeba', 'Beata', 'Beatrycze', 'Benita', 'Berenika', 
   'Bernadetta', 'Berta', 'Bogna', 'Bogumiła', 'Bogusława', 
   'Boguwola', 'Bolesława', 'Bożena', 'Bronisława', 'Brygida', 
   'Cecylia', 'Celina', 'Cezaryna', 'Czesława', 'Dagna', 
   'Dalida', 'Dalila', 'Damaris', 'Daniela', 'Danuta', 
   'Daria', 'Debora', 'Diana', 'Dina', 'Diomeda', 
   'Dionizja', 'Ditta', 'Dobrawa', 'Domicela', 'Dominika', 
   'Donata', 'Doris', 'Dorota', 'Edyta', 'Eleonora', 
   'Eliza', 'Elwira', 'Elżbieta', 'Emanuela', 'Emilia',
   'Erazma', 'Ernesta', 'Erwina', 'Eryka', 'Estera', 
   'Eufemia', 'Eugenia', 'Eulalia', 'Eunika', 'Ewa', 
   'Ewelina', 'Faustyna', 'Felicja', 'Felicyta', 'Filomena', 
   'Flawia', 'Flora', 'Florentyna', 'Franciszka', 'Fryderyka', 
   'Gabriela', 'Gaudencja', 'Gertruda', 'Gilda', 'Gizela', 
   'Gracja', 'Gracjana', 'Grażyna', 'Greta', 'Halina', 
   'Halszka', 'Hanna', 'Helena', 'Henryka', 'Hermenegilda', 'Hilaria',
   'Hildegarda', 'Honorata', 'Honoryna', 'Hortensja', 'Ida', 
   'Iga', 'Ilona', 'Ilza', 'Ingrid', 'Irena', 
   'Iryda', 'Iwetta', 'Iwona', 'Izabela', 'Izabella', 
   'Izolda', 'Jadwiga', 'Jagna', 'Jagoda', 'Jakobina', 
   'Janina', 'Jarmiła', 'Jarosława', 'Jaśmina', 'Joanna', 
   'Jolanda', 'Jolanta', 'Jowita', 'Józefa', 'Józefina', 
   'Judyta', 'Julia', 'Julianna', 'Julita', 'Justyna', 
   'Kaja', 'Kalina', 'Kamelia', 'Kamila', 'Karena', 
   'Karina', 'Karolina', 'Katarzyna', 'Kazimiera', 'Kesja', 
   'Kinga', 'Kira', 'Klara', 'Klaudia', 'Klementyna', 
   'Klotylda', 'Konstancja', 'Kordula', 'Kornelia', 'Krystyna', 
   'Ksenia', 'Kunegunda', 'Kwiryna', 'Larysa', 'Laura', 
   'Lea', 'Leokadia', 'Leonia', 'Lidia', 'Ligia', 
   'Lilianna', 'Lilla', 'Liza', 'Lolita', 'Lora', 
   'Luba', 'Lucja', 'Lucyna', 'Ludmiła', 'Ludomira', 
   'Ludwika', 'Ludwina', 'Luiza', 'Lukrecja', 'Łucja', 
   'Magda', 'Magdalena', 'Maja', 'Malina', 'Malwina', 
   'Małgorzata', 'Marcela', 'Marcelina', 'Marcjanna', 'Margareta', 
   'Maria', 'Marianna', 'Marietta', 'Marika', 'Mariola', 
   'Marlena', 'Marta', 'Martyna', 'Maryla', 'Maryna', 
   'Marzanna', 'Marzena', 'Matylda', 'Melania', 'Metoda', 
   'Michalina', 'Milena', 'Mira', 'Mirabella', 'Miranda', 
   'Miriam', 'Mirosława', 'Monika', 'Mścisława', 'Nadia', 
   'Nadzieja', 'Natalia', 'Neomiła', 'Nina', 'Noemi', 
   'Nora', 'Ofelia', 'Oktawia', 'Olga', 'Olimpia', 
   'Oliwia', 'Otylia', 'Ozanna', 'Patrycja', 'Paula', 
   'Paulina', 'Pelagia', 'Petronela', 'Przybysława', 'Pryscylla', 
   'Pulcheria', 'Rachela', 'Ramona', 'Rebeka', 'Regina', 
   'Renata', 'Rita', 'Roberta', 'Roksana', 'Roma', 
   'Romana', 'Rozalia', 'Rozanna', 'Róża', 'Rudolfina', 
   'Rut', 'Ryszarda', 'Sabina', 'Salome', 'Salomea', 
   'Sandra', 'Sara', 'Sawa', 'Scholastyka', 'Sewera', 
   'Sława', 'Sławomira', 'Sonia', 'Stanisława', 'Stefania', 
   'Stella', 'Swietłana', 'Sylwana', 'Sylwia', 'Taida', 
   'Talita', 'Tamara', 'Tatiana', 'Teodora', 'Teodozja', 
   'Teresa', 'Urszula', 'Wacława', 'Walentyna', 'Waleria', 
   'Wanda', 'Wera', 'Weronika', 'Wiesława', 'Wiktoria', 
   'Wiola', 'Wioletta', 'Władysława', 'Zdzisława', 'Zefiryna', 
   'Zelmira', 'Zenobia', 'Zenona', 'Zofia', 'Zuzanna', 'Zyta',
   'Żaklina', 'Żalina', 'Żaneta', 'Żanna'
   ]

nazwiska=[
   'Adamczak', 'Adamski', 'Adamus', 'Adynowski', 'Ambicki', 
   'Ambrozik', 'Ambrzykowski', 'Andersz', 'Androzd', 'Andruchow', 
   'Andrzej', 'Andrzejczuk', 'Andrzejewski', 'Anikiel', 'Aninowski', 
   'Antoniewicz', 'Apik', 'Arcimowicz', 'Arioch', 'Aszurkiewicz', 
   'Augustin', 'Augustyn', 'Auksztulewicz', 'Azierski', 'Babicki', 
   'Babiński', 'Bacal', 'Bajdecki', 'Bajorek', 'Bak', 
   'Bakalarczyk', 'Balaga', 'Baliński', 'Banach', 'Baniak', 
   'Baran', 'Baranowicz', 'Baranowski', 'Barański', 'Barasiński',
   'Barczyński', 'Barnas', 'Barszczowski', 'Bart', 'Bartczak',
   'Bartecki', 'Bartkowiak', 'Bartkowicz', 'Bartnik', 'Bartoszak', 
   'Bartoszek', 'Bartoszewski', 'Barycz', 'Barzal', 
   'Basciuk', 'Baszyński', 'Batko', 'Baton', 'Bauke',
   'Bawolski', 'Bazar', 'Bebenek', 'Bednarz', 'Bedyński',
   'Behrens', 'Belchowski', 'Ben', 'Benek', 'Berdak', 
   'Berezowski', 'Bernat', 'Bernau', 'Betlej', 'Beton', 
   'Bialas', 'Bialczyk', 'Bialogoński', 'Bialorucki', 'Bialostocki',
   'Bialy', 'Bicz', 'Bieganowski', 'Bielawski', 'Bielecki', 
   'Bielewicz', 'Bieliński', 'Bielski', 'Bieniewski', 'Biernacki', 
   'Bierski', 'Bieszczanin', 'Bigus', 'Bil', 'Biliński', 
   'Bilski', 'Bisz', 'Blachno', 'Blasiak', 'Blaszczyk', 
   'Blaszkowski', 'Blazej', 'Blazek', 'Blecharz', 'Blinowski', 
   'Bobek', 'Boberski', 'Bobka', 'Bocheński', 'Bocian', 
   'Boczek', 'Bogdaniuk', 'Bogucki', 'Boguslawski', 'Boguszewski', 
   'Bohdziewicz', 'Bojarczuk', 'Bojarski', 'Bojczuk', 'Bomerski', 
   'Boncler', 'Boniecki', 'Borczyk', 'Borecki', 'Borkowski', 
   'Boros', 'Borowicz', 'Borowiec', 'Borowski', 'Borowy', 
   'Boruch', 'Borucki', 'Borys', 'Bozejko', 'Bozym', 
   'Branecki', 'Braszkin', 'Brazulewicz', 'Brendler', 'Brol', 
   'Bronkiewicz', 'Brykowski', 'Brys', 'Brzeski', 
   'Brzoska', 'Brzostek', 'Brzozowski', 'Brzuchalski', 'Brzuzy', 
   'Bubel', 'Buchta', 'Buczek', 'Buczma', 'Buczyński', 
   'Budnik', 'Budny', 'Bugaj', 'Bugiel', 
   'Bujak', 'Bukowski', 'Bulanowski', 'Bulik', 'Bulkowski', 
   'Burek', 'Burgielski', 'Burkietowicz', 'Burkowski', 'Bursztyński', 
   'Bury', 'Burzyński', 'Bychowski', 'Byrski', 'Byzdra', 
   'Błachut', 'Bączar', 'Bąk', 'Caban', 'Cecko', 
   'Celej', 'Cendrowicz', 'Cenkier', 'Chabrowski', 'Chalczyński', 
   'Chamera', 'Charchut', 'Chmielewski', 'Chmielina', 'Chmura', 
   'Chochlik', 'Choczewski', 'Chojak', 'Chojnacki', 'Chojnowski', 
   'Cholewa', 'Cholewiński', 'Chomczyk', 'Choromański', 'Chotomski', 
   'Chrobak', 'Chrostek', 'Chrystianowicz', 'Chrzanowski', 'Chudy', 
   'Chudzicki', 'Chudzio', 'Chwedczuk', 'Chyczewski', 'Chyliński', 
   'Chytryk', 'Chęciński', 'Ciak', 'Cias', 'Ciborowski', 
   'Cichocki', 'Cichoń', 'Ciechanowicz', 'Ciecwierz', 'Cieluch', 
   'Cieplik', 'Ciepłucha', 'Cierny', 'Cierpisz', 'Ciesielski', 
   'Ciesla', 'Cieszyński', 'Ciszkowski', 'Ciągło', 'Coperek', 
   'Cwiertniewski', 'Cwikliński', 'Cybulski', 'Cygan', 'Cyklis', 
   'Cyrnek', 'Czach', 'Czajka', 'Czajkowski', 'Czapelski', 
   'Czapla', 'Czapliński', 'Czarciński', 'Czarek', 'Czarkowski', 
   'Czarnasiak', 'Czarnecki', 'Czarnocki', 'Czarnowski', 'Czarny', 
   'Czartoryski', 'Czech', 'Czekay', 'Czermiński', 'Czerw', 
   'Czerwiński', 'Czeslaw', 'Czortek', 'Czubaj', 'Czuma', 
   'Czyczylo', 'Czyżowicz', 'Dadacz', 'Dadik', 'Daniel', 
   'Danielewski', 'Danowski', 'Danysz', 'Dareked', 'Dariusz', 
   'Darowski', 'Dawidczyk', 'Dawidowski', 'Debkowski', 'Degorski', 
   'Demczuk', 'Deneka', 'Depa', 'Depczyński', 'Derkacz', 
   'Dermin', 'Derwiszyński', 'Deręgowski', 'Dirampa', 'Dlugosz', 
   'Dmowski', 'Dobek', 'Dobkowski', 'Dobranowski', 'Dobrowolski', 
   'Dobry', 'Dobrzański', 'Dobrzelecki', 'Dojnikowski', 'Domagala', 
   'Domański', 'Donabidowicz', 'Dorochowicz', 'Doroszuk', 'Downar', 
   'Dołharz', 'Dończyk', 'Drabarek', 'Drabik', 'Drozd', 
   'Drozdowski', 'Drutko', 'Drygiel', 'Dubiec', 'Duchnowski', 
   'Duda', 'Dudczak', 'Dudek', 'Dudziewicz', 'Dudzik', 
   'Dudziński', 'Dukala', 'Dukat', 'Dulik', 'Duniec', 
   'Durat', 'Durlik', 'Duszyński', 'Dutkalski', 'Dworak', 
   'Dybkowski', 'Dyjeciński', 'Dyjor', 'Dymek', 'Dymidziuk', 
   'Dymkowski', 'Dynowski', 'Dziedziński', 'Dzierżyński', 'Dziewdzicki', 
   'Dziewulski', 'Długosz', 'Dąbek', 'Dąbrowski', 'Dębicki', 
   'Dębowski', 'Emilianowicz', 'Falkowski', 'Feltzke', 'Fengler', 
   'Fidecki', 'Fidelus', 'Fiedorowicz', 'Filipczak', 'Filipecki', 
   'Filipkiewicz', 'Filipowski', 'Finke', 'Fiok', 'Flaszyński', 
   'Florczak', 'Florczyk', 'Florek', 'Fojcik', 'Fonfara', 
   'Formanowski', 'Forysiak', 'Frabiński', 'Frackiewicz', 'Frackowiak', 
   'Franckowski', 'Franczak', 'Frankowski', 'Frantz', 'Fryc', 
   'Frycz', 'Frydel', 'Frątczak', 'Fuksa', 'Furmanek', 
   'Furtek', 'Gabryjańczyk', 'Gaczkowski', 'Gad', 'Gadget', 
   'Gajewski', 'Galant', 'Galczewski', 'Galibarczyk',
   'Galiński', 'Gancarz', 'Gapiński', 'Garbaciak', 
   'Garbacz', 'Garbaczewski', 'Garwol', 'Gasek', 'Gasior', 
   'Gasiorski', 'Gasperowicz', 'Gawczyński', 'Gawel', 'Gawlik', 
   'Gawor', 'Gaworski', 'Gawroński', 'Gawrysiak', 'Gawryszewski', 
   'Gałecki', 'Gałązka', 'Gański', 'Gburzyński', 'Geisler', 
   'Gerula', 'Gibałka', 'Gibiński', 'Gielnik', 'Gierlach', 
   'Gierliński', 'Giełzak', 'Gilewski', 'Gizara', 'Giziński', 
   'Gizyński', 'Glanowski', 'Glebocki', 'Glebowski', 'Glogowski', 
   'Glowacki', 'Glozak', 'Gmiter', 'Gmyr', 'Gnabasik', 
   'Gnas', 'Gniadkowski', 'Goczal', 'Godlewski', 'Godoniuk', 
   'Godula', 'Goduński', 'Gogolewski', 'Gohan', 'Golebiewski', 
   'Golebiowski', 'Goliatowski', 'Golik', 'Goliński', 'Gontarek', 
   'Gorczyński', 'Górka', 'Górniak', 'Gorski', 'Gorący',
   'Góźdź', 'Goździkowski', 'Gołaszewski', 'Gołąbek', 'Gołębiewski',
   'Grabarkiewicz', 'Grabowski', 'Graczyk', 'Grad', 'Graf', 
   'Grechuta', 'Greg', 'Gregor', 'Grenda', 'Grobelny', 
   'Grochal', 'Grochowski', 'Grodzki', 'Gronostaj', 'Gronowski', 
   'Grot', 'Grudziński', 'Gruskos', 'Gruszczolus', 'Gruszecki', 
   'Gruszka', 'Grybek', 'Grygiel', 'Grygólec', 'Gryszkiewicz',
   'Grządziela', 'Grzankowski', 'Grzebalski', 'Grzegorczyk',
   'Grzegorzewski', 'Grzelewski', 'Grzesiak', 'Grześko',
   'Grzeszczuk', 'Grzeszek', 'Grzybek', 'Grzybowski', 'Grzywacz', 
   'Grzędziński', 'Grądzki', 'Gubański', 'Gumny', 'Gumułka', 
   'Gutkowski', 'Guziński', 'Gwiazdziński', 'G+sior', 'G+siorowski', 
   'Głogowski', 'Głowacki', 'Głowinkowski', 'Głudkowski', 'Gębal', 
   'Gębski', 'Góra', 'Górecki', 'Górski', 'Hadesz', 
   'Hadrysiak', 'Hajnrych', 'Hajzyk', 'Halada', 'Hancewicz', 
   'Hanisz', 'Hanke', 'Hankus', 'Haranczyk', 'Harasimowicz', 
   'Hasiec', 'Hauzer', 'Helmecki', 'Hiczuk', 'Hnatiuk', 
   'Hojnacki', 'Holband', 'Holdowański', 'Horodyski', 'Horos', 
   'Horyński', 'Hotiuk', 'Hryc', 'Hryn', 'Hrynek', 
   'Hulewicz', 'Huminiecki', 'Husak', 'Hyla', 'Idzikowski', 
   'Idzior', 'Iganowicz', 'Ignatowicz', 'Igorek', 'Ijon', 
   'Ilski', 'Imieliński', 'Imielski', 'Iwanczewski', 'Iwanejko', 
   'Iwaniuk', 'Iwicki', 'Izdebski', 'Jabloński', 'Jabłoński', 
   'Jachimski', 'Jachowicz', 'Jachymek', 'Jackowski', 'Jacyno', 
   'Jadczuk', 'Jagielczuk', 'Jakobczak', 'Jakoniuk', 'Jakubek', 
   'Jakubik', 'Jakubowski', 'Jakubski', 'Janas', 'Jancewicz', 
   'Janczuk', 'Janiak', 'Janik', 'Janikowski', 'Janiszewski', 
   'Janiszowski', 'Jankowiak', 'Jankowicz', 'Jankowski', 'Janos', 
   'Janowski', 'Janus', 'Januszczyk', 'Janusze', 'Januszko', 
   'Jarecki', 'Jarmoszewicz', 'Jarnot', 'Jaros', 
   'Jarosiński', 'Jarosz', 'Jaroszewicz', 'Jaroński', 'Jarzebski', 
   'Jarzecki', 'Jarząbek', 'Jasiek', 'Jasiński', 'Jasiński', 
   'Jaskolski', 'Jastrzebski', 'Jatkowski', 'Jaworowicz', 'Jaworski', 
   'Jazdzyk', 'Jecek', 'Jęczmien', 'Jędrek', 'Jędruszczak',
   'Jędrysiak', 'Jędrzejewski', 'Jędzok', 'Jemioł', 'Jepik',
   'Jermacz', 'Jerzycki', 'Jerzyk', 'Jesionek', 'Jewula', 
   'Jez', 'Jeziak', 'Jezierski', 'Jeziorski', 'Jezowski', 
   'Jozwiak', 'Juras', 'Jurasz', 'Jurczak', 'Jurek', 
   'Jurgielewicz', 'Jurkowski', 'Juskiewicz', 'Juszkiewicz', 'Juśkiewicz', 
   'Jędralski', 'Jędrzejak', 'Józwiak', 'Jóźwik', 'Kacperski', 
   'Kaczmarczyk', 'Kaczmarek', 'Kaczmasz', 'Kaczorowski', 'Kado', 
   'Kadziela', 'Kafarski', 'Kaflik', 'Kalamon', 'Kalecki', 
   'Kaledkiewicz', 'Kalinowski', 'Kalisiak', 'Kalisz', 'Kaliszewicz', 
   'Kaliński', 'Kalnik', 'Kaluga', 'Kaluski', 'Kamaszewski', 
   'Kamela', 'Kamiński', 'Kamionek', 'Kamiński', 'Kampczyk', 
   'Kamys', 'Kandalski', 'Kania', 'Kaniuk', 'Kantor', 
   'Kantorski', 'Kapczuk', 'Kapec', 'Kapil', 'Kapski', 
   'Kapusta', 'Karas', 'Karasek', 'Karasewicz', 'Karaś', 
   'Karbowski', 'Karczewski', 'Karczmarczyk', 'Karger', 'Karolski', 
   'Karpowicz', 'Karski', 'Karwacki', 'Kasperski', 'Kasprzak', 
   'Kasprzycki', 'Kaszowski', 'Kawalec', 'Kazimierowicz', 'Kaznowski', 
   'Kedra', 'Kedzierski', 'Kielar', 'Kieliński', 'Kierzkowski', 
   'Kijanowski', 'Kijewski', 'Kimla', 'Kirejczyk', 'Kita', 
   'Kiziukiewicz', 'Klar', 'Klausa', 'Kleczewski', 'Klekiel', 
   'Klekota', 'Kliber', 'Klimaszewski', 'Klimczak', 'Klimczyk', 
   'Klokowski', 'Klos', 'Klosowski', 'Klukowicz', 'Kluz', 
   'Knap', 'Knapik', 'Kni', 'Kniżewski', 'Knut', 
   'Knysak', 'Kobus', 'Kobyliński', 'Kochanowicz', 'Kochnowicz', 
   'Kocjan', 'Kohut', 'Kojdecki', 'Kolaczkowski', 'Kolakowski', 
   'Kolankiewicz', 'Kolano', 'Kolarz', 'Kolodyński', 'Kolodziej', 
   'Kolorz', 'Komar', 'Komisarski', 'Komosiński', 'Komuda', 
   'Konarski', 'Kondracki', 'Konieczka', 'Koniewicz', 'Konikowski', 
   'Konysz', 'Kopcych', 'Kopec', 'Koperstyński', 'Kopszak', 
   'Kopyłowicz', 'Kordecki', 'Kordiukiewicz', 'Korn', 'Korona', 
   'Koronczewski', 'Korpalski', 'Koryl', 'Korzecki', 'Korzonek', 
   'Kosecki', 'Kosek', 'Kosela', 'Koselski', 'Kosibowicz', 
   'Kosiński', 'Kosmala', 'Kosnik', 'Kostek', 'Kostrzewski', 
   'Koszewar', 'Koszewski', 'Koszowski', 'Kotarbiński', 'Koteras', 
   'Kowal', 'Kowalczyk', 'Kowalewski', 'Kowalik', 'Kowalski', 
   'Kownacki', 'Kowner', 'Kowol', 'Koziarek', 'Kozik', 
   'Kozikowski', 'Koziński', 'Kozioł',
   'Kozusznik', 'Kozłowski', 'Kościarz', 'Kościółek', 
   'Kośmicki', 'Kołodziej', 'Kołosowski', 'Krajanowski', 'Krajewski', 
   'Krakowski', 'Kram', 'Kramer', 'Krang', 'Krasiński', 
   'Krasowski', 'Kraszewski', 'Krauze', 'Krawczyk', 'Kreis', 
   'Krempa', 'Kremser', 'Kretowicz', 'Kridel', 'Kritodiades', 
   'Krogul', 'Krol', 'Krolik', 'Kropacz', 'Kropidlowski', 
   'Kroplewski', 'Kruczyński', 'Kruk', 'Krukowski', 'Krupa', 
   'Krupiński', 'Krupka', 'Krupowicz', 'Kryczkowski', 'Krysiak', 
   'Krystosiak', 'Kryszczuk', 'Kryza', 'Krzat', 'Krzemien', 
   'Krzemiński', 'Krzymowski', 'Krzywda', 'Krzywdziak', 'Krzywiński', 
   'Krzywkowski', 'Krzyzaniak', 'Krzyzanowski', 'Krzyżan', 'Krzyżaniak', 
   'Kręcichwast', 'Kręcicki', 'Kręża', 'Księżyk', 'Kubacki', 
   'Kubera', 'Kubiak', 'Kubica', 'Kubik', 'Kubis', 
   'Kucharczyk', 'Kucharek', 'Kucharski', 'Kuchciak', 'Kuchnio', 
   'Kucypera', 'Kucza', 'Kuczek', 'Kuczera', 'Kuczyński', 
   'Kudlicki', 'Kudrys', 'Kudłacik', 'Kuflikowski', 'Kujawa', 
   'Kukiel', 'Kukiełka', 'Kulaszka', 'Kulazyński', 'Kulesza', 
   'Kuligowski', 'Kulik', 'Kulikowski', 'Kulpa', 'Kumosa', 
   'Kundera', 'Kunowski', 'Kupniewski', 'Kur', 'Kurasz', 
   'Kurdziel', 'Kurek', 'Kurnatowski', 'Kurosad', 'Kurowski', 
   'Kurtz', 'Kuryło', 'Kurzacz', 'Kus', 'Kusiak', 
   'Kusiński', 'Kusmierz', 'Kusnierz', 'Kuszel', 'Kutrzuba', 
   'Kutyla', 'Kuzka', 'Kuzmicz', 'Kuzmierz', 'Kwapień', 
   'Kwaśniak', 'Kwiatkowski', 'Kwiecien', 'Kwieciński', 'Kwietniak', 
   'Kwietniu', 'Kylo', 'Kłys', 'Kądzielski', 'Kędzia', 
   'Kędzierski', 'Kępień', 'Kętla', 'Lacny', 'Laczkowski', 
   'Lampart', 'Lankosz', 'Lasek', 'Lasica', 'Laskarzewski', 
   'Lasko', 'Laskowski', 'Laszewski', 'Lawa', 'Lawrynowicz', 
   'Lazar', 'Lebioda', 'Lechowicz', 'Ledworowski', 'Lefanowicz', 
   'Lejman', 'Leliwa', 'Lelusz', 'Lenda', 'Lentka', 
   'Lenz', 'Lepiarz', 'Lesien', 'Leski', 'Lesniewski', 
   'Leszczyński', 'Leszczyszyn', 'Leszy', 'Lewandowski', 'Lewek', 
   'Lewkowicz', 'Liber', 'Lichacz', 'Lichocki', 'Lichoń', 
   'Lichy', 'Ligienza', 'Likus', 'Lipiński', 'Lipka', 
   'Lipkowski', 'Lipski', 'Lis', 'Lisiewski', 'Lisior', 
   'Liskiewicz', 'Lisowski', 'Litwin', 'Litwiniak', 'Litwiński', 
   'Lobo', 'Lojewski', 'Lonek', 'Loniewski', 'Lopaciński', 
   'Lorent', 'Loret', 'Loster', 'Lubaczewski', 
   'Lubak', 'Lubczyński', 'Lubszczyk', 'Ludwik', 'Lutelmowski', 
   'Luto', 'Luty', 'Macewicz', 'Machacz', 'Machał', 
   'Machnikowski', 'Maciak', 'Maciejewski', 'Maciejko', 'Maciola', 
   'Macioszczyk', 'Macious', 'Mackiewicz', 'Mackowiak', 'Maczek', 
   'Maczkiewicz', 'Maczkin', 'Madaliński', 'Madej', 'Magdziarek', 
   'Magier', 'Maik', 'Maj', 'Majchrzak', 'Majdaniuk', 
   'Majdański', 'Majere', 'Majewski', 'Majka', 'Majkowski', 
   'Majkut', 'Majtyka', 'Makiej', 'Makosa', 'Makowski', 
   'Maksymilian', 'Makula', 'Malak', 'Malanowicz', 'Malarz', 
   'Malek', 'Malicki', 'Maliczowski', 'Malinoski', 'Malinowski', 
   'Maliszewski', 'Malus', 'Mamro', 'Maniszewski', 'Mar', 
   'Marcinkowski', 'Marczak', 'Marczyński', 'Marecki', 'Marek', 
   'Margas', 'Markowski', 'Markuc', 'Markus', 'Marmucki', 
   'Maron', 'Mart', 'Marty', 'Martys', 'Martyński', 
   'Marys', 'Marzec', 'Masalski', 'Maslowski', 'Mastykarz', 
   'Maszenda', 'Matacz', 'Matczak', 'Matlak', 'Matuszak', 
   'Matuszczak', 'Matuszczyk', 'Matuszek', 'Matuszewski', 'Matyjaszczyk', 
   'Matysiak', 'Mazek', 'Mazur', 'Mazurek', 'Mazurkiewicz', 
   'Mazurski', 'Medela', 'Meizner', 'Melek', 'Mendzelek', 
   'Mentrak', 'Merta', 'Mglej', 'Miara', 'Miarka', 
   'Michal', 'Michalak', 'Michalczyk', 'Michalkiewicz', 'Michalowski', 
   'Michalski', 'Michałkiewicz', 'Michel', 'Michocki', 'Midera', 
   'Mieczkowski', 'Mielczarek', 'Mientus', 'Mierzejewski', 'Mieszek', 
   'Mieszko', 'Migduła', 'Mijakowski', 'Mika', 'Mikolajczak', 
   'Mikosz', 'Mikołajczyk', 'Mikulski', 'Milczanowski', 'Milewski', 
   'Minc', 'Minkowski', 'Minowski', 'Mirecki', 'Mirkowski', 
   'Mirowski', 'Misewicz', 'Misiak', 'Misiurewicz', 'Mistun', 
   'Mitana', 'Mizera', 'Miziolek', 'Miś', 'Mlynarczyk', 
   'Modzelewski', 'Molasy', 'Molest', 'Molicki', 'Monter', 
   'Montwiłł', 'Morawiec', 'Morawiecki', 'Mordalski', 'Moskal', 
   'Moskwa', 'Moszko', 'Moszumański', 'Motyl', 'Mońka',
   'Mroczkowski', 'Mrozowski', 'Mrzyglocki', 'Msciwujewski', 'Mucha', 
   'Muchin', 'Muck', 'Mularczyk', 'Mundo', 'Murawa', 
   'Murawski', 'Murdock', 'Murgała', 'Musiał', 'Musiałkowski', 
   'Muszyński', 'Mycek', 'Mydlarz', 'Myśliński', 'Nadejczyk', 
   'Naglik', 'Nagorny', 'Nahlik', 'Najdecki', 'Najduk', 
   'Nalecz', 'Nankieiwcz', 'Narebski', 'Nasiński', 'Nawrocki', 
   'Nawój', 'Neska', 'Neskom', 'Nidecki', 'Niedojadlo', 
   'Niemiec', 'Nienałtowski', 'Nieplowicz', 'Nieszporek', 'Niezabitowski', 
   'Niezborala', 'Niklewicz', 'Niklewski', 'Nitecki', 'Nitka', 
   'Nizio', 'Niziołek', 'Niziński', 'Nojszewski', 'Nolewajka', 
   'Nosek', 'Nosowski', 'Nowacki', 'Nowaczyk', 'Nowak', 
   'Nowakowski', 'Nowara', 'Noway', 'Nowicki', 'Nowosad', 
   'Nowosielski', 'Nycz', 'Nyga', 'Nęcek', 'Obara', 
   'Obrebski', 'Obrębski', 'Obsiadły', 'Ochman', 'Ochmiński', 
   'Ociepa', 'Ogrck', 'Ogrodniczuk', 'Ogłaza', 'Okon', 
   'Olbryś', 'Olczak', 'Older', 'Olearczuk', 'Olech', 
   'Olejnik', 'Olkowski', 'Olobry', 'Olszewski', 'Onderski', 
   'Onopiak', 'Opala', 'Orchel', 'Orliński', 'Orszulka', 
   'Orzol', 'Orłowski', 'Osadowski', 'Osiecki', 'Osiński', 
   'Osiński', 'Osmak', 'Osowski', 'Ostaszewski', 'Ostrowski', 
   'Otocki', 'Owczarczyk', 'Owczarek', 'Owsianik', 'Ozdowski', 
   'Ozimek', 'Pabijaniak', 'Pachla', 'Pacholak', 
   'Paciorek', 'Pacyna', 'Paczesniak', 'Pakosz', 'Pakulski', 
   'Pakuła', 'Palczyński', 'Palka', 'Panas', 'Panasiewicz', 
   'Pander', 'Panek', 'Papaj', 'Papierz', 'Papik', 
   'Papis', 'Paprocki', 'Paris', 'Paroń', 'Partyka', 
   'Parys', 'Parzyszek', 'Pasecki', 'Pasek', 'Pasiut', 
   'Pastuszka', 'Paszko', 'Paszkowski', 'Pater', 'Pawelczyk', 
   'Pawels', 'Pawelski', 'Pawian', 'Pawlak', 'Pawlic', 
   'Pawlik', 'Pawlinka', 'Pawlowski', 'Pawlus', 'Pawłow', 
   'Pawłowski', 'Pałka', 'Pedlowski', 'Pekala', 'Pelech', 
   'Penkala', 'Peska', 'Pianko', 'Piasecki', 'Piasek', 
   'Piaskowski', 'Piatek', 'Piatkowski', 'Piechowski', 'Piechula', 
   'Pieciun', 'Pieczykolan', 'Pieczyński', 'Piejko', 'Piekarski', 
   'Piekart', 'Piekarz', 'Piekutowski', 'Piendyk', 'Pienkowski', 
   'Pierewicz', 'Piergies', 'Pierzchala', 'Piesik', 'Pietkiewicz', 
   'Pietrasik', 'Pietraszek', 'Pietrusiak', 'Pietruszewski', 'Pietrzak', 
   'Pietrzyk', 'Pietrzykowski', 'Pikul', 'Pilarczyk', 'Pilarski', 
   'Pilarz', 'Pilat', 'Piorunek', 'Piosik', 'Piotrowski', 
   'Pisarek', 'Pisarski', 'Piskozub', 'Piszczałkowski', 'Piwowarczyk', 
   'Pińskwar', 'Płatek', 'Plewiński', 'Plewus', 'Pliszka',
   'Pluszyński', 'Pluta', 'Plutecki', 'Pniewski', 'Pochmurski', 
   'Pociej', 'Pocwiardowski', 'Podek', 'Podgorski', 'Podkowiński', 
   'Podniesiński', 'Podziewski', 'Pogrzebacz', 'Pojda', 'Polak', 
   'Polkowski', 'Polowczuk', 'Pomaski', 'Pomocnik', 'Pomykoł', 
   'Popielarski', 'Popielas', 'Popko', 'Poplawski', 'Popławski', 
   'Porada', 'Porębski', 'Poreda', 'Portal', 'Poślednik',
   'Poswiata', 'Poszytek', 'Potentas', 'Potrymajło', 'Potęga', 
   'Powązka', 'Powrózek', 'Poznański', 'Prachniak', 'Prajsnar',
   'Pralat', 'Predki', 'Preisner', 'Promiński', 'Promyczek', 
   'Przadka', 'Przemyski', 'Przepiórka', 'Przesmycki', 'Przybyl', 
   'Przybylski', 'Przybysz', 'Przybyłek', 'Przygodzki', 'Przytarski', 
   'Pstrucha', 'Ptak', 'Ptasznik', 'Puchalski', 'Puchar', 
   'Puchnowski', 'Puhacz', 'Pulapa', 'Pulawski', 'Pulikowski', 
   'Purzycki', 'Pustuł', 'Puławski', 'Pycka', 'Pyda', 
   'Pyra', 'Pysz', 'Pytka', 'Pytliński',
   'Pytowski', 'Pyżanowski', 'Płaszczyca', 'Płaza', 'Płociniczak', 
   'Pólkowski', 'Półtorak', 'Rachwal', 'Raczek', 'Raczyński', 
   'Racław', 'Radecki', 'Radko', 'Radowan', 'Radzikowski', 
   'Radzio', 'Rafalski', 'Rajchel', 'Rajtar', 'Rajzer', 
   'Rakowski', 'Ranger', 'Raszewski', 'Ratajczak', 'Ratuszniak', 
   'Rauchfleisz', 'Rawis', 'Rawiński', 'Rebis', 'Reda', 
   'Redlarski', 'Redziak', 'Rejczak', 'Rekosz', 'Reluga', 
   'Repiński', 'Retkowski', 'Rezul', 'Ripel', 'Rodak', 
   'Rodzik', 'Rogala', 'Rojecki', 'Rola', 'Roland', 
   'Rolski', 'Romanowicz', 'Romanowski', 'Rosiak', 'Roszkowski', 
   'Roter', 'Rozalski', 'Rozański', 'Rozdzyński', 'Rozek', 
   'Rozpara', 'Rozwadowski', 'Rozycki', 'Rubach', 'Rubikon', 
   'Rudnik', 'Rudowski', 'Rudziejewski', 'Rudziński', 'Rujner', 
   'Rumian', 'Rumski', 'Rusin', 'Rusinek', 'Rusinowski', 
   'Rusty', 'Rutkowski', 'Rybak', 'Rybarz', 'Rybicki', 
   'Rybiński', 'Rybiński', 'Rycek', 'Rychcik', 'Rychlik', 
   'Rydecki', 'Rydlewski', 'Rylski', 'Rymarek', 'Rynkiewicz', 
   'Ryszard', 'Rzentarzewski', 'Rzepecki', 'Rzepka', 'Rzesista', 
   'Rzoska', 'Rzuczkowski', 'Rózga', 'Sabiniarz', 'Sachanowicz', 
   'Saciuk', 'Sadecki', 'Sadkowski', 'Sadowski', 'Sagan', 
   'Sajdak', 'Sakowski', 'Salaban', 'Salata', 'Salkiewicz', 
   'Samoraj', 'Sampławski', 'Sanecki', 'Sankowski', 'Sapota', 
   'Sarbinowski', 'Sarna', 'Sarnowski', 'Sarzała', 'Saternus', 
   'Sauer', 'Sawicki', 'Sałamacha', 'Schmidt', 'Schwartz', 
   'Scibek', 'Sciborek', 'Segit', 'Selega', 'Seliga', 
   'Semczuk', 'Semik', 'Seremak', 'Serwadczak', 'Siatecki', 
   'Sibilski', 'Sibiński', 'Siczek', 'Sidor', 'Sidorczuk', 
   'Siejak', 'Sielewiesiuk', 'Sielski', 'Siembida', 'Siemieniak', 
   'Sieniawski', 'Sienkiewicz', 'Sienko', 'Sierakowscy', 'Sierociński', 
   'Sierocki', 'Sierota', 'Sijko', 'Sikora', 'Sitarz', 
   'Siwak', 'Siwy', 'Skarzyński', 'Skaznik', 'Sklorz', 
   'Skoblewski', 'Skoczeń', 'Skoczylas', 'Skoniecki', 'Skorus', 
   'Skowronek', 'Skowroński', 'Skowroński', 'Skrzat', 'Skrzek', 
   'Skrzykowski', 'Skrzymowski', 'Skrzypczak', 'Skrzypek', 'Skula', 
   'Skut', 'Skwarka', 'Sladowski', 'Slaw', 'Slawek', 
   'Slawiński', 'Sliwiński', 'Sliwka', 'Slomczyński', 'Slomski', 
   'Slowiński', 'Slusarczyk', 'Smoliński', 'Sobala', 'Sobański', 
   'Sobczyk', 'Sobiecki', 'Sobieszczański', 'Sobkowiak', 'Sobkowski', 
   'Sobol', 'Sobolewski', 'Sobota', 'Sochański', 'Sochowski', 
   'Socik', 'Sodel', 'Sojski', 'Sokal', 'Sokalski', 
   'Sokol', 'Sokolowski', 'Solak', 'Solarz', 'Soroczyński', 
   'Soroka', 'Soska', 'Sosnierz', 'Sosnowski', 'Sowa', 
   'Sowiński', 'Sołtysiak', 'Spaliński', 'Spawn', 'Speier', 
   'Srech', 'Sroczyński', 'Sroka', 'Srokosz', 'Stachowiak', 
   'Stachowicz', 'Stachura', 'Stafiński', 'Stalica', 'Stanczyk', 
   'Stangel', 'Stangreciak', 'Staniak', 'Staniecki', 'Staniszewski', 
   'Stankiewicz', 'Staworzyński', 'Steblecki', 'Stec', 'Steczen', 
   'Stefański', 'Stefański', 'Stela', 'Stepien', 'Stepniewski', 
   'Stilgar', 'Stokłosa', 'Stolarczyk', 'Stolarek', 'Stolarski', 
   'Stolarz', 'Stopa', 'Storm', 'Stożek', 'Strogow', 
   'Strojek', 'Strugalski', 'Struś', 'Strycharski', 'Stryja', 
   'Stryjewski', 'Strzelecki', 'Strzeliński', 'Stręciwilk', 'Stube', 
   'Studziński', 'Stypula', 'Stępień', 'Suchomski', 'Suchowski', 
   'Suchozebrski', 'Suchożebrski', 'Sula', 'Sulej', 'Sulek', 
   'Suliga', 'Sulkowski', 'Sulowski', 'Sumara', 'Supernak', 
   'Surma', 'Surowiec', 'Surowiecki', 'Suszyński', 'Sut', 
   'Suîkowski', 'Swiatkowski', 'Swiderski', 'Swietek', 'Swift', 
   'Swirek', 'Switaj', 'Sylwestrowicz', 'Sylwestrzak', 'Syriusz', 
   'Syslo', 'Syta', 'Szabat', 'Szachnowski', 'Szade', 
   'Szadkowski', 'Szafarczyk', 'Szajner', 'Szalewicz', 'Szaraniec', 
   'Szarblewski', 'Szatkowski', 'Szałaśny', 'Szałomski', 'Szczap', 
   'Szczech', 'Szczechura', 'Szczepanek', 'Szczepaniak', 'Szczepankiewicz', 
   'Szczepiński', 'Szczepkowski', 'Szczerbicki', 'Szczesiul', 'Szczesniak', 
   'Szcześniak', 'Szczudło', 'Szczukowski', 'Szczurek', 'Szczygieł', 
   'Szczygłowski', 'Szczypiorowski', 'Szczęsny', 'Szefer', 'Szegda', 
   'Szela', 'Szel+g', 'Szemlet', 'Szenkaryk', 'Szerszeński', 
   'Szeruga', 'Szewczak', 'Szewczyk', 'Szeworski', 'Szim', 
   'Szklarczyk', 'Szklarek', 'Szleper', 'Szmatola', 'Szmit', 
   'Szoltysek', 'Szopka', 'Szostak', 'Szostakiewicz', 'Szostakowski', 
   'Szot', 'Szpakowski', 'Szperkowski', 'Sztwiertnia', 'Szubiński', 
   'Szulc', 'Szuliński', 'Szumski', 'Szuszkiewicz', 'Szutka', 
   'Szwedo', 'Szychowski', 'Szydlowski', 'Szyjewski', 'Szym', 
   'Szymala', 'Szymanek', 'Szymański', 'Szymański', 'Szymczak', 
   'Szymon', 'Szymoszczyk', 'Szymukowicz', 'Szymura', 'Szyndela', 
   'Szypula', 'Szypulski', 'Szyszlo', 'Szywalski', 'Sławiński', 
   'Sławomir', 'Słowik', 'Słupicki', 'Służewski', 'Talarek', 
   'Tanio', 'Tarasek', 'Tarasiejski', 'Tarchała', 'Tarkowski', 
   'Tatar', 'Tatarczak', 'Taunu', 'Taunus', 'Tkaczyk', 
   'Tkisiel', 'Tobolik', 'Toczek', 'Tolu', 'Tomasik', 
   'Tomaszewki', 'Tomaszewski', 'Tomczyk', 'Tomiak', 'Topolski', 
   'Torus', 'Toton', 'Trabiński', 'Tramer', 'Trojanowski', 
   'Truchel', 'Truposz', 'Truskaw', 'Trych', 
   'Tryk', 'Trzaska', 'Trzeci', 'Trześniowski', 'Turno', 
   'Turon', 'Turowski', 'Tusien', 'Tuszyński', 'Tułnik', 
   'Tymancjo', 'Tymiński', 'Uliszak', 'Usowski', 'Wachol', 
   'Wacowski', 'Wajszle', 'Walasek', 'Walaszek', 'Waldek', 
   'Walecki', 'Walinowicz', 'Walus', 'Wanasz', 'Warelich', 
   'Wasiak', 'Wasielewski', 'Wasikiewicz', 'Wasikowski', 'Wasilewski', 
   'Wasilka', 'Wasiu', 'Waszkiewicz', 'Wawak', 'Wawer', 
   'Wawro', 'Wawruch', 'Wawrzynczak', 'Wawrzynkiewicz', 'Wdowiak', 
   'Weglarczyk', 'Wegner', 'Welc', 'Werner', 'Weselski', 
   'Wesołowski', 'Wiatrowski', 'Wichowski', 'Widera', 'Widomski', 
   'Wiecek', 'Wieclawski', 'Wieczorek', 'Wieczór', 'Wierba', 
   'Wiercigroch', 'Wierzbicki', 'Wieteska', 'Wiktor', 'Wiktorow', 
   'Wilczek', 'Wilczyński', 'Wilczyński', 'Wileczek', 'Wilgocki', 
   'Wilk', 'Wilkosz', 'Wilowski', 'Windpol', 'Winiak', 
   'Winiarski', 'Wiosna', 'Wisniewski', 'Wisz', 'Wiszniewski', 
   'Wit', 'Witalina', 'Witalski', 'Witczak', 'Witek', 
   'Witerski', 'Witkiewicz', 'Witkowicz', 'Witkowski', 'Witocha', 
   'Wiśnica', 'Wiśniewski', 'Wiśniewski', 'Więcek', 'Wloskowicz', 
   'Wochowiec', 'Wodziński', 'Wojcicki', 'Wojciech', 'Wojciechowski', 
   'Wojczyk', 'Wojnar', 'Wojnowski', 'Wojtala', 'Wojtalik', 
   'Wojtas', 'Wojtiuk', 'Wojtkiewicz', 'Wojtkowicz', 'Wojtowicz', 
   'Wolak', 'Woliński', 'Wolnik', 'Wolski', 'Wos', 
   'Wosik', 'Wozniak', 'Wołniacki', 'Wołniak', 'Wradek', 
   'Wroblewski', 'Wroclaw', 'Wroczyński', 'Wrona', 'Wronko', 
   'Wronkowski', 'Wrzesiński', 'Wrzochal', 'Wrzosek', 'Wróbel', 
   'Wróblewski', 'Wujt', 'Wyglądała', 'Wygrabek', 'Wyka', 
   'Wyrzutowicz', 'Wysocki', 'Włodarczak', 'Wątorowski', 'Węgrzyn', 
   'Wójcik', 'Wójcikiewicz', 'Wótkowski', 'Zabawski', 'Zabiński', 
   'Zablocki', 'Zaborowski', 'Zaborski', 'Zabza', 'Zachar', 
   'Zacharzewski', 'Zachciał', 'Zaczkiewicz', 'Zadrozny', 'Zając', 
   'Zajączkowski', 'Zak', 'Zakolski', 'Zakrzewski', 'Zaleski', 
   'Zalewa', 'Zalewski', 'Zalot', 'Zamecki', 'Zamłyński', 
   'Zankiewicz', 'Zapart', 'Zapór', 'Zareba', 'Zarebski', 
   'Zaremba', 'Zarski', 'Zarzeczny', 'Zaręba', 'Zatorski', 
   'Zatryb', 'Zawada', 'Zawadiak', 'Zawadzki', 'Zawicki', 
   'Zbart', 'Zbierajewski', 'Zbierzchowski', 'Zbieżek', 'Zbikowski', 
   'Zbilski', 'Zbrodel', 'Zbych', 'Zdrodowski', 'Zdunek', 
   'Zduński', 'Zdziarski', 'Zekanowski', 'Zelazko', 'Zielen', 
   'Zieleskiewicz', 'Zieliński', 'Zieliński', 'Ziemian', 'Zienkiewicz', 
   'Zietara', 'Zimecki', 'Zimolzak', 'Zinek', 'Ziobro', 
   'Ziobrowski', 'Ziolek', 'Ziolkowski', 'Ziomek', 'Zięba', 
   'Ziębiński', 'Ziętek', 'Zloty', 'Zmokly', 'Zmuda', 
   'Zmyslowski', 'Zolisz', 'Zolna', 'Żółtowski', 'Żukociński',
   'Żur', 'Żurawski', 'Zwarycz', 'Zwinka', 'Zwiruk',
   'Zych', 'Zyk', 'Zysek', 'Złakowski', 'Ząbek', 
   'Święcański', 'Świętosławski', 'Łabarzewski', 'Łabedz', 'Łabęcki', 
   'Ładoś', 'Łazar', 'Łodziana', 'Łukaszewicz', 'Łukaszewski', 
   'Łukomski', 'Łącki', 'Żmich', 'Żurawski', 'Żórawski', 
   'Ćmoch', 'Ćwiertka', 
   ]

emailproviders=[['gmail.com']*55+
   ['hotmail.com']*10+
   ['yahoo.com']*3+
   ['poczta.o2.pl']*1+
   ['poczta.interia.pl']*2+
   ['poczta.wp.pl']*4+
   ['poczta.gazeta.pl']*4+
   ['poczta.onet.pl']*15+
   ['autograf.pl']*1][0]

telefony=[
['500','PTK Centertel','Orange'],
['501','PTK Centertel','Orange'],
['502','PTK Centertel','Orange'],
['503','PTK Centertel','Orange'],
['504','PTK Centertel','Orange'],
['505','PTK Centertel','Orange'],
['506','PTK Centertel','Orange'],
['507','PTK Centertel','Orange'],
['508','PTK Centertel','Orange'],
['509','PTK Centertel','Orange'],
['510','PTK Centertel','Orange'],
['511','PTK Centertel','Orange'],
['512','PTK Centertel','Orange'],
['513','PTK Centertel','Orange'],
['514','PTK Centertel','Orange'],
['515','PTK Centertel','Orange'],
['516','PTK Centertel','Orange'],
['517','PTK Centertel','Orange'],
['518','PTK Centertel','Orange'],
['519','PTK Centertel','Orange'],
['530','P4','Play'],
['531','P4','Play'],
['532','Polska Telefonia Cyfrowa','T-Mobile'],
['533','P4','Play'],
['534','P4','Play'],
['535','P4','Play'],
['538','Polska Telefonia Cyfrowa','T-Mobile'],
['539','Polska Telefonia Cyfrowa','T-Mobile'],
['600','Polska Telefonia Cyfrowa','T-Mobile'],
['601','Polkomtel','Plus'],
['602','Polska Telefonia Cyfrowa','T-Mobile'],
['603','Polkomtel','Plus'],
['604','Polska Telefonia Cyfrowa','T-Mobile'],
['605','Polkomtel','Plus'],
['606','Polska Telefonia Cyfrowa','T-Mobile'],
['607','Polkomtel','Plus'],
['608','Polska Telefonia Cyfrowa','T-Mobile'],
['609','Polkomtel','Plus'],
['660','Polska Telefonia Cyfrowa','T-Mobile'],
['661','Polkomtel','Plus'],
['662','Polska Telefonia Cyfrowa','T-Mobile'],
['663','Polkomtel','Plus'],
['664','Polska Telefonia Cyfrowa','T-Mobile'],
['665','Polkomtel','Plus'],
['667','Polkomtel','Plus'],
['668','Polska Telefonia Cyfrowa','T-Mobile'],
['669','Polkomtel','Plus'],
['691','Polkomtel','Plus'],
['692','Polska Telefonia Cyfrowa','T-Mobile'],
['693','Polkomtel','Plus'],
['694','Polska Telefonia Cyfrowa','T-Mobile'],
['695','Polkomtel','Plus'],
['696','Polska Telefonia Cyfrowa','T-Mobile'],
['697','Polkomtel','Plus'],
['698','Polska Telefonia Cyfrowa','T-Mobile'],
['721','Polkomtel','Plus'],
['723','Polkomtel','Plus'],
['724','Polkomtel','Plus'],
['725','Polkomtel','36i6'],
['726','Polkomtel','36i6'],
['730','P4','Play'],
['731','P4','Play'],
['738','PKP Polskie Linie Kolejowe',''],
['780','PTK Centertel',''],
['781','Polkomtel','Plus'],
['782','Polkomtel','Plus'],
['784','Polska Telefonia Cyfrowa','T-Mobile'],
['785','Polkomtel','Plus'],
['788','Polska Telefonia Cyfrowa','Heyah'],
['790','P4','Play'],
['791','P4','Play'],
['792','P4','Play'],
['793','P4','Play'],
['794','P4','Play'],
['796','P4','Play'],
['797','PTK Centertel','Orange'],
['798','PTK Centertel','Orange'],
['880','Polska Telefonia Cyfrowa','Heyah'],
['882','Polska Telefonia Cyfrowa','Mobilking'],
['885','Polkomtel','Plus'],
['886','Polska Telefonia Cyfrowa','Heyah'],
['887','Polkomtel','iPlus'],
['888','Polska Telefonia Cyfrowa','Heyah'],
['889','Polska Telefonia Cyfrowa','Heyah'],
]

class DaneOsobowe:
   def __init__(self,aplec=1,arokurodzeniastart=1970,arokurodzeniaend=2004):
      self.Imiona=imiona
      self.Nazwiska=nazwiska
      self.dnazwiska={}
      self.dpesel={}
      for anazwisko in nazwiska:
         afirst=anazwisko[:1]
         l=self.dnazwiska.get(afirst,[])
         l.append(anazwisko)
         self.dnazwiska[afirst]=l
      self.ImionaMeskie=imionameskie
      self.ImionaZenskie=imionazenskie
      self.EMailProviders=emailproviders

      self.aplec=aplec
      self.arokurodzeniastart=arokurodzeniastart
      self.arokurodzeniaend=arokurodzeniaend
   def Init(self):
      self.UrodzenieRok=random.randint(self.arokurodzeniastart,self.arokurodzeniaend)
      self.UrodzenieMiesiac=random.randint(1,12)
      amrange=calendar.monthrange(self.UrodzenieRok,self.UrodzenieMiesiac)
      self.UrodzenieDzien=random.randint(amrange[0],amrange[1])
      self.DataUrodzenia='%4d-%02d-%02d'%(self.UrodzenieRok,self.UrodzenieMiesiac,self.UrodzenieDzien)
      if self.aplec<0:
         self.Plec=random.randint(0,1)
      else:
         self.Plec=self.aplec
      if self.Plec:
         self.PlecKM='M'
      else:
         self.PlecKM='K'
      self.Imie=self.GetImie()
      self.Nazwisko=self.GetNazwisko()
      self.ImieASCII=XMLUtil.CP1250_To_ASCII(self.Imie.lower())
      self.NazwiskoASCII=XMLUtil.CP1250_To_ASCII(self.Nazwisko.lower())
      self.Osoba=self.Imie+' '+self.Nazwisko
      self.Login=self.ImieASCII+self.NazwiskoASCII
      self.EMail=self.GetEMail()
      self.PESEL=self.GetPESEL()
      while self.dpesel.has_key(self.PESEL):
         self.PESEL=self.GetPESEL()
      self.dpesel[self.PESEL]=1
      self.GetTelefon()
   def GetImie(self):
      if self.Plec:
         return self.Imiona[random.randint(0,len(self.Imiona)-1)]
      return self.ImionaZenskie[random.randint(0,len(self.ImionaZenskie)-1)]
   def GetNazwisko(self,azenskie=0):
      if random.randint(1,10)<7:
         l=self.dnazwiska.get(self.Imie[:1],self.Nazwiska)
         s=l[random.randint(0,len(l)-1)]
      else:
         s=self.Nazwiska[random.randint(0,len(self.Nazwiska)-1)]
      if not self.Plec:
         if s[-2:]=='ki':
            s=s[:-1]+'a'
      return s
   def GetEMail(self):
      return '%s.%s@%s'%(self.ImieASCII,self.NazwiskoASCII,emailproviders[random.randint(0,len(emailproviders)-1)])
   def GetTelefon(self):
      atel=telefony[random.randint(0,len(telefony)-1)]
      self.TelefonPrefix=atel[0]
      self.TelefonMNT=atel[1]
      self.TelefonMarka=atel[2]
      self.Telefon='+48 '+self.TelefonPrefix+str(random.randint(100000,999999))
      return self.Telefon
   def GetPESEL(self):
      amadd=0
      if 1800<=self.UrodzenieRok<=1899:
         amadd=80
      elif 1900<=self.UrodzenieRok<=1999:
         amadd=0
      elif 2000<=self.UrodzenieRok<=2099:
         amadd=20
      elif 2100<=self.UrodzenieRok<=2199:
         amadd=40
      elif 2200<=self.UrodzenieRok<=2299:
         amadd=60
      ro=str(self.UrodzenieRok)[-2:]
      mi=self.UrodzenieMiesiac+amadd
      dz=self.UrodzenieDzien
      se=random.randint(100,999)
      pl=random.randint(0,4)*2+self.Plec
      pesel='%s%02d%02d%d%d'%(ro,mi,dz,se,pl)
      suma=int(pesel[0])*1+int(pesel[1])*3+int(pesel[2])*7+int(pesel[3])*9+int(pesel[4])*1+int(pesel[5])*3+int(pesel[6])*7+int(pesel[7])*9+int(pesel[8])*1+int(pesel[9])*3
      sk=10-(suma%10)
      if sk==10:
         sk=0
      pesel+=str(sk)
      return pesel

