# -*- coding: windows-1250 -*-
# saved: 2020/11/02 21:15:54

from CLASSES_Library_ICORBase_Interface_ICORInterface import *
import random

ulice=[
"Żabia","Żagańska","Żarnowiecka","Żbikowa","Żegiestowska",
"Żeglarska","Żegrze","Żelazna","Żerkowska","Żlebowa",
"Żmigrodzka","Żmudzka","Żnimska","Żniwna","Żonkilowa",
"Żorska","Żuławska","Żupańskiego","Żurawia","Żwirowa",
"Żydowska","Żytnia","Żywiecka","Żywocicka","3 Maja",
"9 Maja","A.Andrzejewskiego","A.Asnyka","A.Biedrzyckiego","A.Cieszkowskiego",
"A.Danysz","A.Hercena","A.Karpińskiej","A.Kopy","A.Kordeckiego",
"A.Kosińskiego","A.Logi","A.Małeckiego","A.Madalińskiego","A.Mickiewicza",
"A.Szamarzewskiego","A.Szylinga","A.Tomaszewskiego","A.Tułodzieckiej","A.Łaskarza.",
"A.Wolkowskich","A.Wrzoska","Admiralska","Agrestowa","Akacjowa",
"Al.Armii Poznań","Al.K.Marcinkowskiego","Al.Niepodległości","Al.Pod Lipami","Al.Republik",
"Andrychowska","Architektów","Arkońska","Armeńska","Astrowa",
"Augustowska","Azaliowa","B.Krysiewicza","B.Krzywoustego","B.Lewandowskiego",
"B.Limanowskiego","B.Malinowskiego","B.Winklera","Błońska","Błotna",
"Błękitna","Bałtycka","Babicka","Babimojska","Baczyńska",
"Balonowa","Barana","Baranowska","Barska","Bartnicza",
"Bartoszycka","Barwicka","Bastionowa","Baśniowa","Bełchatowska",
"Begoniowa","Belwederska","Berestecka","Beskidzka","Biłgorajska",
"Biała","Białczańska","Białogradzka","Białostocka","Białośliwska",
"Biebrzańska","Bielniki","Bielska","Bieszczady","Bilewiczówny",
"Biskupińska","Bitwy pod Siekierkami","Bitwy pod Studziankami","Biwakowa","Blacharska",
"Bliźniąt","Bluszczowa","Bnińska","Bożeny","Bożydara",
"Bożymira","Bobrownicka","Bobrzańska","Bociania","Boźnicza",
"Boczna","Boczowska","Bodawska","Bogumiła","Bohaterów",
"Bohaterów Westerplatte","Bojanowska","Bojerowa","Bolesława Krzywoustego","Bolesławy",
"Bolka","Bolkowicka","Bonin","Borówki","Boranta",
"Borowa","Borowikowa","Borsucza","Boruty","Borysława",
"Bosa","Bosmańska","Botaniczna","Braniborska","Bratuminy",
"Będlewska","Będzińska","Browarna","Brzask","Brzeska",
"Brzozowa","Bułgarska","Bużańska","Budziszyńska","Budzyńska",
"Bukowa","Bukowska","Buska","Butryma","Bydgoska",
"Bystra","Bystrzycka","Byteńska","Bytomska","Bzowa",
"C.K.Norwida","C.Ratajskiego","Cedrowa","Cedzyńska","Ceglana",
"Ch.Andersena","Chłodna","Chartowo","Charzykowska","Chełmińska",
"Chemiczna","Chlebowa","Chmielna","Chociebora","Chodzieska",
"Chojnicka","Chomęcicka","Chotomińska","Chróściejowskich","Chęcińska",
"Chrobacka","Chromowa","Chwaliszewo","Chyżańska","Ciasna",
"Ciechocińska","Cienista","Cieplicka","Cieszyńska","Cisowa",
"Cmentarna","Cmielowska","Cybińska","Cymsa","Cyniowa",
"Cyprysowa","Człopska","Człuchowska","Czajcza","Czapla",
"Czaplinecka","Czarna Rola","Czarniejewska","Czarnkowska","Czartoria",
"Czechosłowacka","Czechowska","Czekalskie","Czekanowskiego","Czeladzka",
"Czempińska","Czeremchowa","Czereśniowa","Czernichowska","Czerska",
"Czesnikowska","Czorsztyńska","Częstochowska","Czwartaków","Czysta",
"Źródlana","D.Chłapowskiego","Długa","Dąbrówki","Daleka",
"Daliowa","Danuty","Darłowska","Darniowa","Darzyńska",
"Darzyborska","Daszewicka","Dedala","Dożynkowa","Dobiegniewska",
"Dobra","Dobre Pole","Dobrochny","Dobromiły","Dobrowita",
"Dobrzyńska","Dojazd","Doleńska","Dolina","Dolna",
"Dolna Wilda","Dolska","Dominikańska","Doniestrzańska","Dowbora Muśnickiego",
"Drawska","Dęblińska","Dębowa","Drobna","Droga Dębińska",
"Drogowców","Drużbackiej","Drużynowa","Druskienicka","Drzewna",
"Dukielska","Dunajecka","Duszna","Dwa Tory","Dworcowa",
"Dworkowa","Dworska","Działkowa","Działoszycka","Działowa",
"Dziadoszańska","Dzieci Wrzesińskich","Dziedzicka","Dziekańska","Dziewanny",
"Dziewińska","Dzięgłowa","E.Caliera","E.Estkowskiego","E.Orzeszkowej",
"E.Plater","E.Raczyńskiego","E.Szczanieckiej","E.Taczanowskiego","Elbląska",
"Estońska","Ewangelicka","Ezopa","F.Żwirki","F.Adamanisa",
"F.Chopina","F.Hynka","F.Nowowiejskiego","F.Rakoczego","F.Ratajczaka",
"F.Stablewskiego","F.Stróżyńskiego","F.Znanieckiego","Fabianowa","Fabryczna",
"Falista","Faszynowa","Fedrusa","Filarecka","Filipińska",
"Fiołkowa","Floksowa","Folwarczna","Fornalskiej","Forteczna",
"Fr.Danielaka","Fr.Morawskiego","Franciszkańska","Franowo","Fredry",
"Fregatowa","Frezjowa","Fromborska","G.Bergera","G.Konatkowskiej",
"G.Potworowskiego","Góralska","Górczyńska","Górecka","Górki",
"Górna Wilda","Górnicza","Górska","Główieniec","Główna",
"Gładka","Głazowa","Głogowa","Głogowska","Głowicka",
"Głęboka","Głuchowska","Głuszyna","Gąsiorowskich","Gajowa",
"Galileusza","Galla Anonima","Garaszewo","Garbary","Gardowska",
"Garncarska","Gdańska","Gdyńska","Gen.T.Kutrzeby","Geodetów",
"Gerberowa","Giżycka","Gladiolowa","Glebowa","Gliniana",
"Gliwicka","Gminna","Gnieźnieńska","Gniewka","Gniewska",
"Gołężycka","Gołębia","Gołuchowska","Goździkowa","Goleszowska",
"Golęcińska","Goplańska","Gorajska","Goryczewskiego","Gorzowska",
"Gorzysława","Gospodarska","Gostyńska","Grąbczowska","Grabowa",
"Grabowska","Graniczna","Graniowa","Granowska","Grobla",
"Grochowe Łąki","Grochowska","Grodnicka","Grodziska","Gromadzka",
"Gronowa","Gronowska","Grotkowska","Grottgera","Gęsia",
"Grudzieniec","Grunwaldzka","Gruszkowa","Gruzińska","Gryfińska",
"Grześkiewicza","Grzybowa","Gubińska","Guliwera","Gwardii Ludowej",
"Gwarna","Gwiaździsta","H.Arctowskiego","H.Cegielskiego","H.Dąbrowskiego",
"H.Dybowskiego","H.Śniegockiego","H.Jordana","H.Kołłątaja","H.Kuncewiczówny",
"H.Rzepeckiej","H.Siemiradzkiego","H.Sienkiewicza","H.Szafran","H.Ułaszyna",
"H.Łowmiańskiego","H.Wieniawskiego","Haliny","Halna","Halszki",
"Hangarowa","Harcerska","Hawelańska","Helska","Hetmańska",
"Hiacyntowa","Hoża","Hodowlana","Hrubieszowska","Hrynakowskiego",
"Hulewiczów","Husarska","Hutnicza","I.Dobrogojskiego","I.Kassyusza",
"I.Kraszewskiego","I.Łukaszewicza","I.Wierzejewskiego","I.Zielewicza","Iłżańska",
"Iłowska","Ścinawska","Idzikowskiego","Ikara","Śląska",
"Śliska","Śliwkowa","Ślężańska","Ślubicka","Ślusarska",
"Śmiełowska","Śmigi","Śmigielska","Infladzka","Śniadeckich",
"Inowrocławska","Śpiewaków","Śródka","Średnia","Średzka",
"Śremska","Irysowa","Św.Antoniego","Św.Czecha","Św.Czesława",
"Św.Jacka","Św.Jerzego","Św.Marcina","Św.Marii Magdaleny","Św.Michała",
"Św.Rocha","Św.Szczepana","Św.Trójcy","Św.Wawrzyńca","Św.Wincentego",
"Św.Wojciecha","Świątniczki","Światopełka","Świdnicka","Świerkowa",
"Świerzawska","Świetlana","Święciańska","Świętobodzińska","Świętochny",
"Świętogórska","Świętojańska","Świętosławska","Świt","Iwonicka",
"J.Żeylanda","J.Bruna","J.Brzechwy","J.Chełmońskiego","J.Chociszewskiego",
"J.Długosza","J.Drwęskiego","J.Garczyńskiego","J.H.Dąbrowskiego","J.Kilińskiego",
"J.Kochanowskiego","J.Kościeleckiego","J.Krasickiego","J.Krauthofera","J.Leńskiego",
"J.Lelewela","J.Lubrańskiego","J.Malczewskiego","J.Marklakiewicza","J.Matejki",
"J.Niemcewicza","J.Omańkowskiej","J.Paszty","J.Porazińskiej","J.Przybylskiego",
"J.Rogalińskiego","J.Rymarkiewicza","J.Słowackiego","J.Skrzetuskiego","J.Sokołowskiego",
"J.Sowińskiego","J.Stachowiaka","J.Suszko","J.Szajnowicza","J.Tuwima",
"J.Umińskiego","J.Wieczorka","J.Wojtkiewicza","J.Wrońskiego","J.Wybickiego",
"Jałowcowa","Jabłonkowska","Jachtowa","Jagodowa","Janikowska",
"Janisławy","Janosika","Janowska","Januszewskiego","Jaraczewska",
"Jarocińska","Jaromira","Jarosławska","Jarowa","Jarzębowa",
"Jasielska","Jaskółcza","Jaskiniowa","Jasna Rola","Jasne Błonia",
"Jastrowska","Jastrzębia","Jaszyńskiego","Jaśkowiaka","Jaśminowa",
"Jawornicka","Jaworowa","Jeżycka","Jeleniogórska","Jesionowa",
"Jodłowa","Jędrzejowska","Jugosłowiańska","Junacka","Junikowska",
"Juracka","Juraszów","Jutrzenka","K.Żegockiego","K.Arciszewskiego",
"K.Brossa","K.Dróżbickiego","K.Iłłakowiczówny","K.Janickiego","K.Jarochowskiego",
"K.Kurpińskiego","K.Libelta","K.Lubeckiego","K.Makuszyńskiego","K.Potockiej",
"K.Pułaskiego","K.Rylejewa","K.Szałasa","K.Szymanowskiego","K.Troczyńskiego",
"K.Tymienieckiego","Kórnicka","Kłońska","Kłuszyńska","Kącik",
"Kacza","Kaczeńcowa","Kadłubka","Kadecka","Kajakowa",
"Kalinowa","Kaliowa","Kaliska","Kamieńska","Kamienicka",
"Kamienna","Kamiennogórska","Kanałowa","Kanclerska","Kantaka",
"Kapitańska","Kaplera","Karawetowa","Karkonoska","Karlińska",
"Karmelicka","Karpacka","Karpia","Kartuzka","Karwieńska",
"Kasztanowa","Kasztelańska","Kaszubska","Katowicka","Kazimierza Wielkiego",
"Ketlinga","Kielecka","Kierska","Kimliczów","Kirchomolska",
"Klasztorna","Klenowska","Klin","Klonowa","Kluczborska",
"Kmicica","Kmieca","Kołobrzeska","Kołodzieja","Kobylepole",
"Kobylińska","Koźmińska","Kolejowa","Kolska","Kolskiego",
"Komandoria","Komandorska","Komornicka","Konarowa","Konarzewska",
"Konińska","Konwaliowa","Kopanina","Kopciuszka","Kopernika",
"Koprzywnicka","Koralowa","Korczaka","Korczyńska","Koronkarska",
"Koronna","Korwetowa","Korzenna","Kosiarzy","Kosowska",
"Kostrzyńska","Kosynierska","Koszalińska","Kościańska","Kościelna",
"Kościerzyńska","Kotlarska","Kotlińska","Kotowo","Kowalewicka",
"Kozia","Koziernicka","Koziorożca","Królewny Śnieżki","Królowej Jadwigi",
"Krótka","Krągowska","Krańcowa","Krajenecka","Krakowska",
"Kramarska","Krasnoludków","Kresowa","Krobska","Krokusowa",
"Krośnieńska","Kępińska","Krucza","Krusznicka","Kryłowa",
"Krynicka","Krzepicka","Krzesiny","Krzyżowa","Krzywa",
"Krzywińska","Ks.P.Ściegiennego","Ks.Posadzego","Ks.Zakrzewskiego","Książęca",
"Księcia Józefa","Ku Cytadeli","Ku Dębinie","Kujawska","Kukułcza",
"Kunickiego","Kupały","Kurpiowska","Kurtlandzka","Kutnowska",
"Kwiatowa","Kwidzyńska","Kwiryny","L.Krzywickiego",
"L.Podpięty","L.Przyłuskiego","Lachowicka","Laskowa","Latawcowa",
"Laudańska","Lawendowa","Lazurowa","Lechicka","Lednicka",
"Legnicka","Lemierzycka","Leszczyńska","Leszka","Leśna",
"Leśnowolska","Leśnych Skrzatów","Lewkoniowa","Lidzka","Liliowa",
"Limbowa","Lipowa","Lisa Witalisa","Lisia","Listopadowa",
"Litewska","Lodowa","Lomżyńska","Lotnicza","Lotosowa",
"Lęborska","Lubartowska","Lubczykowa","Lubiatowska","Lubieńska",
"Lubosińska","Lubowska","Ludgardy","Ludmiły","Ludosławy",
"Lumumby","Lutycka","M.Barzyńskiego","M.Bohuczewiczówny","M.Buczka",
"M.Chwiałkowskiego","M.Drzymały","M.Jackowskiego","M.Jaroczyńskiego","M.Kasprzaka",
"M.Konopnickiej","M.Krajewskiego","M.Langiewicza","M.Mottego","M.Niedziałkowskiego",
"M.Nowotki","M.Palucha","M.Różka","M.Reja","M.Rodziewiczówny",
"M.Smoluchowskiego","M.Wicherkiewicz","M.Wołodyjowskiego","Młyńska","Mączna",
"Mała","Małe Garbary","Małopolska","Małoszyńska","Maciejkowa",
"Macierzankowa","Madziaeska","Madziarska","Magazynowa","Magnoliowa",
"Maków Polnych","Makowa","Makowej Panienki","Malborska","Malechowska",
"Malinowa","Malwowa","Maratońska","Marcelińska","Margaretkowa",
"Margonińska","Mariacka","Marszałkowska","Marynarska","Marzanny",
"MaszewskA","Masztalerska","Masztowa","Maszynowa","Mazowiecka",
"Mazurska","Meliorantów","Metalowa","Meteorytowa","MIńska",
"Miła","Miłosławska","Miłowita","Miastkowska","Michałowo",
"Michałowska","Miczurina","Miechowska","Miecznikowska","Miedziana",
"Mielecka","Mieleszyńska","Mielęckiego","Mieszka I","Mieszkowska",
"Mikołowska","Mikstacka","MIlczańska","Milczańska","Milicka",
"Minikowo","Miodowa","Międzychodzka","Międzyzdrojska","Miętowa",
"Miśnieńska","Mołdawska","Modlińska","Modra","Modrakowa",
"Modrzewiowa","Mogileńska","Mokra","Moraska","Morasko",
"Morawska","Morelowa","Morenowa","Morszczyńska","Morwowa",
"Moryńska","Morzyczańska","Mostowa","Mrągowska","Mrowińska",
"Mścibora","Murawa","Muszkowska","Muszyńska","Mylna",
"Myśliborska","Myśliwska","N.Pajzderskiego","Na Miasteczku","Na Podgórniku",
"Na Skarpie","Na Stoku","Nałęczowska","Nad Bogdanką","Nad Jeziorem",
"Nad Krzesinką","Nad Potokiem","Nad Seganką","Nad Wierzbakiem","Nadbrzeże",
"Nadolnik","Nadwarciańska","Nagietkowa","Namysłowska","Napoleońska",
"Naramowicka","Narcyzowa","Narewska","Newtona","Niżańska",
"Nidziańska","Niecała","Niemeńska","Niezłomnych","Niska",
"Nizinna","Notecka","Nowe Zagórze","Nowina","Nowogrodzka",
"Nowokramska","Nowosądecka","Nowosolska","Nowotarska","O.Kopczyńskiego",
"Oławska","Ożarowska","Obodrzycka","Obornicka","Oborzyca",
"Obronna","Obrzańska","Obrzeże","Ochota","Odległa",
"Odolanowska","Odrzycka","Ognik","Ogrodnicza","Ogrodowa",
"Okólna","Okonecka","Okopowa","Okulska","Olchowa",
"Oleśnicka","Olimpijska","Olsztyńska","Olszynka","Olszynowa",
"Olzańska","Opalenicka","Opatowska","Opawska","Opolska",
"Orkana","Orla","Orlat","Orna","Orężna",
"Orzechowa","Osiecka","Osinowa","Oskierki","Ossowskiego",
"Ostatnia","Ostrówek","Ostrobramska","Ostroroga","Ostrowska",
"Ostrzeszowska","Oświęcimska","Otwocka","Owcza","Owczarska",
"Ownicka","Owocowa","Owsiana","Ozimina","P.Bardowskiego",
"P.Findera","P.Skargi","P.Strzeleckiego","P.Tomnickiego","P.Wysockiego",
"Północna","Półwiejska","Płocka","Płomienna","Płowecka",
"Pałucka","Pabianicka","Pacajewa","Paczkowska","Paderewskiego",
"Palacza","Pamiątkowa","Pana Kleksa","Pana Twardowskiego","Panny Marii",
"Paplińskiego","Paryżancka","Pasieka","Pasterska","Pawła z Brudzewa Włodkowica",
"Pawłowicka","Pawia","Perłowska","Perkuna","Perzycka",
"Pińczowska","Piątkowska","Piaskowa","Piastowska","Piaśnicka",
"Piekary","Pietruszyńskiego","Pilicka","Pilotów","Pilska",
"Pionierska","Piotrowo","Piotrowska","Piękna","Piwna",
"Piwoniowa","Pl.Bernardyński","Pl.C.Ratajskiego","Pl.H.Dąbrowskiego","Pl.Kolegiacki",
"Pl.Orawski","Pl.Spiski","Pl.Wielkopolski","Pl.Wiosny Ludów","Pl.Wolności",
"Pl.Zbawiciela","Platanowa","Plebańska","Pleszewska","Plonowa",
"Pniewska","Połabska","Połaniecka","Połczyńska","Południowa",
"Pobielska","Pochyła","Podbórska","Podchorążych","Podgórna",
"Podgajska","Podhalańska","Podjazdowa","Podkomorska","Podlaska",
"Podleśna","Podmiejska","Podmokła","Podojska","Podolańska",
"Podstolińska","Podwale","Pogodna","Pokrzywno","Polańska",
"Polanka","Polanowska","Polna","Polska","Pomorska",
"Poniecka","Popiela","Popradzka","Poprzeczna","Poranek",
"Poronińska","Poręba","Porzeczkowa","Powidzka","Powstańców Wielkopolskich",
"Powstańców Wlkp.","Powstańcza","Pozdawnicka","Poznańska","Poznańskie Sady",
"Próżańska","Prądzyńskiego","Projektowana","Promienista","Promienistaa",
"Prośnicka","Pruszkowa","Prymasa S.Wyszyńskiego","Prząśniczki","Przełom",
"Przełęcz","Przedborska","Przedpole","Przelot","Przemysłowa",
"Przemyska","Przepadek","Przeskok","Przesmyk","Prześwit",
"Przybrodzka","Przygraniczna","Przystań","Przytoczna","Psarskie",
"Pszczelna","Pszczyńska","Pszenna","Ptasia","Ptaszkowska",
"Puławska","Pułtuska","Pucka","Pusta","R.Berwińskiego",
"R.Kocha","R.Kowalskiego","R.Luksemburg","R.Maya","R.Sławińskiego",
"R.Szymańskiego","R.Traugutta","Różana","Różany Targ","Różyczkowa",
"Równa","Rabczańska","Racławicka","Racjonalizatorów","Radłowa",
"Radomska","Radosna","Radowita","Radyńska","Radziwoja",
"Raka","Rakoniewicka","Ranowska","Raszyńska","Rataje",
"Ratuszowa","Rawicka","Regatowa","Rejtana","Reknicka",
"Rembertowska","Rewalska","Robocza","Rodawska","Rogozińska",
"Rojna","Rokietnicka","Rokity","Rolna","Rondo Żegrze",
"Rondo Śródka","Rondo Kaponiera","Rondo Rataje","Rondo Starołęka","Roosevelta",
"Ropczycka","Rosnowska","Roślinna","Rozewska","Rozmarynowa",
"Roztocka","Rozwadowska","Rubież","Rugijska","Rumcajsa",
"Rumiankowa","Rumuńska","Ruska","Rybaki","Rybnicka",
"Rybojadzka","Ryby","Rycerska","Rydzyńska","Rymanowska",
"Rynarzewska","Rynek Śródecki","Rynek Łazarski","Rynek Wschodni","Rynkowa",
"Rysia","Rzeczańska","Rzeczna","Rzepińska","Rzeszowska",
"S.Żeromskiego","S.Bożywoja","S.Czarnieckiego","S.Dobrzyckiego","S.Engla",
"S.Lindego","S.Mielżyńskiego","S.Okrzei","Sławińska","Sławomira",
"Słodyńska","Słoneczna","Słonimska","Słowiańska","Słowicza",
"Słupecka","Słupska","Sąsiedzka","Sabiny","Sadnicka",
"Sadowa","Salicka","Samotna","Sanatoryjna","Sandomierska",
"Sanocka","Santocka","Saperska","Sarbinowska","Sarmacka",
"Sarnia","Sasankowa","Sawickiej","Sempołowskiej","Senatorska",
"Serafitek","Serbska","Sianowska","Siedmiogrodzka","Sielska",
"Sienna","Sieradzka","Sierakowska","Sieroca","Siewna",
"Silniki","Siwierska","Składowa","Skalna","Skarbka",
"Skarszewska","Skawińska","Skibowa","Skoczowska","Skorpiona",
"Skotarska","Skośna","Skrajna","Skromna","Skryta",
"Skwierzyńska","Smardzewska","Smołdzinowska","Smoka Wawelskiego","Smolna",
"Snopowa","Sołecka","Sołtysia","Sobiesława","Sobolowa",
"Sobotecka","Sochaczewska","Sokola","Solna","Soroki",
"Sosnowa","Sośnicka","Sowia","Sowice","Spławie",
"Spadachronowa","Spadzista","Spiżowa","Spichrzowa","Spokojna",
"Sportowa","Sędziwoja","Srebrna","Sępia","St.Chudoby",
"St.Karwowskiego","St.Knapowskiego","St.Konarskiego","St.Małachowskiego","St.Niedbalskiego",
"St.Nowakowskiego","St.Pawłowskiego","St.Przybyszewskiego","St.Staszica","St.Struga",
"St.Szczepanowskiego","St.Taczaka","St.Wachowiaka","St.Wigury","St.Wyspiańskiego",
"Stalowa","Starachowicka","Starkowska","Starołęcka","Starołęka",
"Starogardzka","Staromiejska","Startowa","Stary Rynek","Staszowska",
"Stawna","Sterowa","Stetańskiego","Stewnicka","Stobnicka",
"Stokrotkowa","Stolarska","Storczykowa","Straży Ludowej","Stęszewska",
"Strusia","Strykowska","Strzała","Strzałkowska","Strzecha",
"Strzegomska","Strzelca","Strzelczyka","Strzelecka","Strzelińska",
"Strzeszyńska","Studzienna","Sułowska","Sucha","Surechowska",
"Swantibora","Swarożyca","Swarzędzka","Swojska","Sycowska",
"Synów Pułku","Sypniewo","Syrenia","Sytkowska","Szadecka",
"Szafirowa","Szaflarska","Szamocińska","Szamotulska","Szarotkowa",
"Szarych Szeregów","Szczawnicka","Szczecińska","Szczepankowo","Szczęsna",
"Szczytnicka","Szeherezady","Szelągowska","Szenwalda","Szewska",
"Szklarniowa","Szkolna","Szkutnicza","Szpaków","Szpitalna",
"Szreniawska","Szubińska","Szybowcowa","Szydłowiecka","Szydłowska",
"Szyperska","T.Drobnika","T.Kościuszki","T.Mateckiego","Tarczowa",
"Tarninowa","Tarnobrzeska","Tarnowska","Tatrzańska","Tczewska",
"Temicka","Templińska","Terespolska","Tokarska","Tomaszowska",
"Topolowa","Torfowa","Torowa","Toruńska","Towarowa",
"Trójpole","Tęczowa","Trębacka","Truskawiecka","Truskawkowa",
"Trybunalska","Trzcianiewska","Trzebawska","Trzebińska","Trzebiatowska",
"Trzemeszeńska","Tucholska","Tulipanowa","Turniowa","Turystyczna",
"Tuwima","Twardogórska","Tylne Chwaliszewo","Tyrwecka","Łódzka",
"Ułańska","Łąkowa","Łabędzia","Łacina","Łady",
"Łagodna","Łagowska","Łanowa","Ławica","Łazienna",
"Ugory","Ulmutowska","Umultowska","Unii Lubelskiej","Unisława",
"Łobzenicka","Łomżyńska","Łomnicka","Łopawska","Łopianowa",
"Łosiowa","Łowicka","Łozowa","Uradzka","Urbanowska",
"Łęczycka","Urocza","Urwista","Ustrońska","Ustrzycka",
"Łużycka","Łubinowa","Łuczanowska","Łuczkowska","Łucznicza",
"Ługańska","Ługiańska","Łysogórska","W.Biegańskiego","W.Bogusławskiego",
"W.Czajkowa","W.Engstroma","W.Gieburowskiego","W.Grimma","W.Kossaka",
"W.Majakowskiego","W.Pniewskiego","W.Pstrowskiego","W.Rzewuskiego","W.Syrokomli",
"W.Witosa","W.Wróblewskiego","Wójcika","Wójtowska","Wł.Kotwicza",
"Wł.Nehringa","Wł.Reymonta","Wł.Sikorskiego","Władymira","Włazowa",
"Włodarska","Włoszakowicka","Włościańska","Wałbrzyska","Wałecka",
"Wadowicka","Wagi","Wagrowska","Walecka","Wandy",
"Warecka","Warmińska","Warowna","Warpińska","Warpnowska",
"Warszawska","Warzywna","Wawerska","Wawrzyniaka","Wczasowa",
"Weglowa","Wejherowska","Wenecjańska","Wenedów","Wiatraczna",
"Wichrowa","Widłakowa","Widawska","Widna","Wieżowa",
"Wiece","Wieczorynki","Wiejska","Wielichowska","Wielka",
"Wielkopolska","Wieluńska","Wieprawska","Wierchowa","Wieruszowska",
"Wierzbięcice","Wierzbowa","Wiesławy","Wiklinowa","Wilcza",
"Wilczak","Wileńska","Wilków Morskich","Wilkońskich","Winiarska",
"Winna","Winogrady","Wiosenna","Wioślarska","Wirska",
"Więzowska","Wisłocka","Witkowska","Wiślana","Wiślicka",
"Wiśniowa","Witosława","Witoszka","Wituchowska","Wołczyńska",
"Wołkowa","Wołowska","Wołyńska","Woźna","Woźnicka",
"Wodna","Wodnika","Wojnowicka","Wojska Polskiego","Wojskowa",
"Wojtkiewicza","Wolbramska","Wolińska","Wolnica","Wolska",
"Wolsztyńska","Worcella","Węgorzewska","Wrończyńska","Wrocławska",
"Wroniecka","Wrzesińska","Wrzosowa","Wschodnia","Wschowska",
"Wspólna","Wszystkich Świętych","Wyłom","Wyżyny","Wybieg",
"Wygon","Wykopy","Wysoka","Wyszeborska","Wyszomierska",
"Wyzwolenia","X.Dunikowskiego","Z.Krasińskiego","Z.Nałkowskiej","Z.Noskowskiego",
"Z.Sokolnickiej","Z.Wojciechowskiego","Z.Zalewskiego","Złota","Złotnicka",
"Złotowska","Ząbkowicka","Za Bramką","Za Cybiną","Za Cytadelą",
"Za Groblą","Załęże","Zachodnia","Zacisze","Zagórze",
"Zagórzycka","Zagłoby","Zagonowa","Zagrodnicza","Zakopiańska",
"Zakręt","Zamenhoffa","Zamknięta","Zamkowa","Zamojska",
"Zana","Zaniemyska","Zawady","Zb.Budzyńskiego","Zb.Cybulskiego",
"Zbaszyńska","Zbożowa","Zbyszka","Zbytowita","Zdrojowa",
"Zdunowska","Zdziechowska","Zdzisławy","Zgodna","Zgorzelecka",
"Zieleńska","Zielona","Ziemowita","Ziębicka","Zjazd",
"Zmartwychwstańców","Zorza","Zwierzyniecka","Zwrotnicza",]

miasta=["Bełchatów","Biała Podlaska","Białystok","Bielsko-Biała","Bolesławiec",
"Bydgoszcz","Bytom","Będzin","Chełm","Chorzów",
"Chrzanów","Ciechanów","Częstochowa","Dąbrowa Górnicza","Dębica",
"Elbląg","Ełk","Gdańsk","Gdynia","Gliwice",
"Gniezno","Gorzów Wielkopolski","Grudziądz","Głogów","Inowrocław",
"Jarosław","Jastrzębie-Zdrój","Jaworzno","Jelenia Góra","Kalisz",
"Katowice","Kielce","Knurów","Konin","Koszalin",
"Kołobrzeg","Kraków","Krosno","Kutno","Kędzierzyn-Koźle",
"Legionowo","Legnica","Leszno","Lubin","Lublin",
"Malbork","Mielec","Mysłowice","Nowa Sól","Nowy Sącz",
"Nysa","Olkusz","Olsztyn","Opole","Ostrowiec Świętokrzyski",
"Ostrołęka","Ostrów Wielkopolski","Otwock","Oświęcim","Pabianice",
"Piekary Śląskie","Piotrków Trybunalski","Piła","Poznań","Pruszków",
"Przemyśl","Puławy","Płock","Racibórz","Radom",
"Radomsko","Ruda Śląska","Rumia","Rybnik","Rzeszów",
"Sanok","Siedlce","Siemianowice Śląskie","Sieradz","Skarżysko-Kamienna",
"Skierniewice","Sopot","Sosnowiec","Stalowa Wola","Starachowice",
"Stargard Szczeciński","Starogard Gdański","Suwałki","Szczecin","Szczecinek",
"Słupsk","Tarnobrzeg","Tarnowskie Góry","Tarnów","Tczew",
"Tomaszów Mazowiecki","Toruń","Tychy","Warszawa","Wałbrzych",
"Wejherowo","Wodzisław Śląski","Wrocław","Włocławek","Zabrze",
"Zamość","Zawiercie","Zduńska Wola","Zgierz","Zielona Góra",
"Świdnica","Świdnik","Świnoujście","Świętochłowice","Łomża",
"Łódź","Żary","Żory","Żyrardów",]

class Adresy:
   def __init__(self,aulicaadd=0,amaxnumer=98,amaxlokal=22):
      self.Ulice=ulice
      self.Miasta=miasta
      self.ulicaadd=aulicaadd
      self.amaxnumer=amaxnumer
      self.amaxlokal=amaxlokal
   def __getattr__(self,name):
      if name=='Ulica':
         return self.GetUlica()
      if name=='Miasto':
         return self.GetMiasto()
      if name=='Adres':
         return self.GetUlica()+', '+self.GetMiasto()
      if name=='Numer':
         return self.GetNumer()
   def GetUlica(self):
      if self.ulicaadd:
         return 'ul. '+self.Ulice[random.randint(0,len(self.Ulice)-1)]+' '+str(random.randint(1,self.amaxnumer))
      else:
         return self.Ulice[random.randint(0,len(self.Ulice)-1)]
   def GetMiasto(self):
      return self.Miasta[random.randint(0,len(self.Miasta)-1)]
   def GetNumer(self):
      anumer=str(random.randint(1,self.amaxnumer))
      r=random.randint(1,7)
      self.Lokal=''
      if r==5:
         anumer+='A'
         self.Lokal=str(random.randint(1,self.amaxlokal))
      elif r==6:
         anumer+='B'
         self.Lokal=str(random.randint(1,self.amaxlokal))
      else:
         r=random.randint(1,3)
         if r==3:
            self.Lokal=str(random.randint(1,self.amaxlokal))
      return anumer

def ICORMain(CID=-1, FieldName='', OID=-1, Value='', UID=-1):
   aclass=aICORDBEngine.Classes[CID]
   aadresy=Adresy()
   for i in range(10):
      print aadresy.Adres
   return



