# -*- coding: windows-1250 -*-
# saved: 2020/11/02 21:15:54

import random

nazwy=["A-Bud","A-Zed","A & M","A & R","A. G. Budowlaniec",
"A.R.T.","AAG-Bud","Abart-Invest","Abbud","Abimex",
"Abit","Abol","Adam-Pol","Adma","Admi",
"Admiral","Ag-Mar","Agpar","Agrad","Agro Inwest-Bud",
"Agroma","Ajmex","Akces","Akord","Alex-Bud",
"Alfa","Alfa-Tan","Alkbud","Alles","Alta-Bud",
"Ama-Bud","Amar","Ambud","AmerEstate","Anbud",
"Andrewex","Aqua-Glas","Arbet","Archa","Archibud",
"Archicenter","Archigraf","Archikom","Arcon","Argo",
"Ari","Art","Artbud","Artom","ASA Inwest",
"Ata","Ataner","Atlant","Atw Partner","Autorobot",
"Awbud","Awim","Awo","Axxess","Azbud",
"BOB Inwest","Balizan","Bamaar","Bartek","Basta",
"Bau-Export","Bau-Mar","Baubud","Baupol","Bazmont",
"BC Inwest","BePa","Beskid-Holding","Besopol","Beton Stal",
"Betonbud 2","BGH-RM","Biel-Bud","Bildex","Bin-Bud",
"Biobbud","Biodom","Biprodex","Bis","Bistal",
"Blaks","Bln System","Bmi","Bmw-Plast","Bock",
"Bok","Bomar","Bomex-Bud","Bormal","Botto",
"Bovis","Bratex","Braun","BT","Bud-Complex",
"Bud-Consulting","Bud-Drew","Bud-Inwest","Bud-Marss","Bud-Max",
"Bud-Stol","Bud-War","Bud-Wars","Bud Lech","Budagros-Bis",
"Budan","Budar","Budbaum","Budcen","Buded",
"Budeko","Budem","Budex","Budexim","Budexpol",
"Budexport","Budim","Budimex","Budimex-Olsztyn","Budimpex",
"Buding","Budinrem","Budinwest","Budirem","Budkons",
"Budlad","Budma","Budmark","Budmark-Amal","Budmed-PBO",
"Budmel","Budmet","Budmet-Carbo","Budmex","Budmex Bis",
"Budo-Complex","Budo Invest","Budochem","Budoinwest","Budokomplex",
"Budom","Budomat","Budomex","Budomont","Budomontaż",
"Budopap","Budopiec","Budopol","Budoprojekt","Budoprzem",
"Budoremont","Budostal","Budostal 3","Budostyl","Budotank",
"Budowa","Budowlani","Budpol","Budrem","Budremex",
"Budrex","Budromir","Budtech","Build Inc","Buis",
"Buo-Big","C.E.L.","Cadena","Capita","Cardo",
"Care","Carpenter Construction","Cel","Celbud","Celmar Union",
"Cenbud","Centrbud","Centrex","Ceramirex","Cetbud",
"CFE Polska","Chapebex","Checzbud","Chemadin","Chemobudowa",
"Chemomontaż","Chemorozruch","Cogik","Complex","Condix",
"Consbud","Constans","Corpores","Cotton","Creo",
"CTW-Polska","Curtis Companies","Dąb-Bud","Dach-Bud","Dach Bud Bis",
"Dak-Bud","Dak-Bud","Dan-Mar","Dana-Bud","Darex",
"Dasker","Datacomp","Debud","Dekadex","Dekamur",
"Dekar","Dekorator","Dekorum-Bud","Delta","Democo Poland",
"Dendrobud","Depespol","Descon","Developer","Developer-Bud",
"Diatech","DIM","Dim-Bud","Ditting Polska","Doctor Q Bud",
"Dom","Dom-Bud","Dom-Marion","Dom Developer","Dom II",
"Domeko","Domex","Dominus","Domprojekt","Domur",
"Dor-Bud","Dorbud","Dortex","Dortom","Dr Ex Pol",
"Drewbud","Dromex","Dromos","Dromost-Płock","Ds-T",
"Ebar-Bau","Ebi","Echo Investment","Eco","Eco-Bud",
"Eco Abi","Ecotech","Edbud","Edoo","Efekt",
"Ego","Ejot","Ekbud","Eko-Bud-Trans","Eko-Dom",
"Eko-Energia","Eko-Ex","Eko-Inwest","Eko-Irbud","Eko-San",
"Eko-Serwis","Eko-System","Ekobud","Ekolog","Ekomelbud",
"Ekoprod","Ekoservice","El-Ka","Elektromontaż","Elektroster",
"Elipsa","Elkom","Elma","Elmo-Poland","Elsan",
"Elstol","Elwox","Elxa","Em-Bud","Embiko",
"Emsa","Energoexport","Energomar-Nord","Energopol","Era-Bud",
"Ergo","Ergorek","Esbud","Eselmex","Espol",
"Eureka Invest","Euro-Bud","Eurobud-21","Eurodock","Eurodom",
"Euromost","Ewal","Exbud-Wschód","Exbud Wrocław","Exico Ltd.",
"Exkol","Exsel","Extra-Bud","Ezam","F. K. Domicilium",
"Faber","Fabud","Fal-Mech","Famar","Famex-Bis",
"Fech-Bud","Fenix","Ferrum","Festal","Festbud",
"Ficenes","Fomax","Fondor","Forex","Fratmur",
"Franki","Freytag Budpol","Frybud 2","Fryz","Gac-Bud",
"Gama Investments","Gamar","Gamus","Gasco Investment","Gekom",
"Geobis","Ger-Pol","Ghelamco-Poland","Glamax","Glob",
"Gobex","Gomex","GPIB","Graden","Gral-Polska",
"Graz","Grembud","Grewbud","Grimbud","Gromar",
"Gutmark","Habud","Halbet","Hall System","Hamer",
"Hand-Bud","Handlomix","Hanscomb Polska","Hare","Harkbud",
"Hekobud","Helsico","Hemiz","Herbud","Hero",
"Hetman","Himal-Rembud","Hirsz-Bud","HMB","Holma",
"House-Service","HPR-Remel","HTS","Hydrad","Hydrobud",
"Hydropol","Hydrowat","I.B.C.","Ibe","Ibi",
"Ido","Ilbud","Ima-Bud","Imbud","IMI International",
"Immobilis","Impex","Impol-Invest","In-Corp","In-Rem",
"Inbud","Infon","Infra","Infra-Tel","Infrabud",
"Infrakol","Inkom","Inmar","Ins-Bud","Insbud",
"Inspec","Instal-Bud","Instal-Zem","Instalbau","Intax",
"Intech","Integra-Eko Inwestment","Integra-Polska","Integral","Inter-Bau Polska",
"Inter-Hermesa","Inter-Profi","Inter-System","Inter-Tech","Inter",
"Interasphalt","Intercam","Interfinn","Interhart Co. Ltd.","Interimpex",
"Interm","Intermarkom","Intop","Inveco","Inved-Bud",
"Invest-Park","Invest-Plus","Investcorp","Investeco","Investor Pro Domo",
"Inwest","Inwest-Bet","Inwest-Bud","Inwest-Complex","Inwest-Lex",
"Inwest-Projekt","Inwest-Usługa","Inwest Bud","Inwest Dfb","Inwest Prim",
"Inwest Projekt","Inwestbud","Inwestdom","Inwesthut","Inwestopoz",
"Inwestor","Inwestprojekt","Inwestprojekt 2000","Inwestsat","Inwestus",
"Inwus","Inzap","IPB","IPM","IPW Projex",
"Irda-Pol-Ltd","Irproj","Irson","Iskra","Italpol",
"Iter-Tech","Iwa","Izobud","Izokor","Izolbud",
"Izoterm","J & P","J. T. B.","J.D.E. Development","Jac-Pol",
"Jaga-Pol","Jaks-Bud","Janex","Jantar","Jar-Bud",
"Jas-Pol","Jastpol","Jaz-Rud","Jedynka","Jest-Bud",
"JIM","Jotel-Invest","Juanja","Juvenes","K.B.B. Projekt Management",
"Kaba","Kadet","Kalasanta","Kam Bud","Kami",
"Kamid","Kan-Bud","Kandro-2","Kapitol","Karbud",
"Karo","Kartech","Kas-Pol","Kasamba","Katil",
"Katon","Kellerbud","Kenos","Kobo","Kolbud",
"Komapol","Kombud","Kompleks","Komplet Inwest","Koncept",
"Kondrex","Konmed","Konsbud","Konstal","Konstans",
"Konstrukt","Kontra 5","Kontur","Koprin","Kordbud",
"Korizola","Korpos","Korys","Koszt-Bud","Kotwica",
"KPBP-Bick","KPIB-Interfin","KPRBUD","Kreator","Kreto-Technik",
"Kris","Krizar","Ksk Investment","Kubus","Kvalitet-Bud",
"Kwadrat","Kws & Partner","L.B.S. Argon","Leader","Lebud",
"Lech","Lechbud","Leg-Bud","Legbud","Legis",
"Leo-Bud","Level","Libra","Lik Bud","Limes",
"Limex","Limm","Lobo","Logos","Lokum",
"Lugra","Lux-Dom","M.T.S.","Mach-Bud","Magmet",
"Magorex","Mal-Tapex","Malt","Mar-Bud","Mar-Ko-Pol",
"Marbat IMM","Marbud","Mardelli","Margo","Marka",
"Markbud","Markos","Markowa","Markpol","Marss",
"Martex","Masbud","Maswerk","Matex-Pol","Matimpex",
"Max-Bud","Maxbud","Maxbud Ltd.","Maxit Polska","Megalit",
"Megam","Megapol","Melbud","Mennica Invest","Merat",
"Metalchem Imp-Ex","Metromex","Mexpol","MGM","MGS",
"Micro Master","Mielcbud","Mig-Bud","Mikrobud","Milbud",
"Milbud Co.","Mimar","Mir-Bud","Mirbud","Mix",
"MJ","Modeh-Polmo","Moderator Bis","Moderndom","Monex",
"Monolit","Mont-Insal","Montokwas","Montostal","Morawski",
"Morze","Most-Bud","Motiw","MPBJiP","Mt Polska",
"MTM II","Mur-Bet","Muraton II","Murator","Murbet",
"Murbex","Murexbud","Myko-Inwest","Mynet","Naos",
"NBD","Niegocin","Noma","Noma Juniprex","Novapol",
"Novum","Nowa","Nowator","Oldbud","Olimp",
"Ols Construction","Omega","Omnix","Opal","Opekol",
"Opex","Oprem","Optimex-C","OPWiK","Orbi",
"Orgbud","Orwox","Over-Bud","P & P","P&P Alians",
"P.O.S.","Pal-Puh","Palex","Paley & Partner","Pamar",
"Partner","Pas","Pascal","Paw-Bud","PBI",
"PBMH","Pbo Investment","Peab","PeBeKa","PeBeRol",
"Peberol II","Pebex","Perfect Sport","Piec-Export","Pikobud",
"PIMB","Piomar","Pit","Plastibet","PM Group Polska",
"POB","Poi","Pol-Bud","Pol-Kaufring","Pol-Rem",
"Polger","Polimex-Naftoremont","Polinvest","Polnord","Pomat",
"PORR Polska","Portal","Powiernik","PRB","Premont",
"Press","Pri","Pribo","PRIM","Prim",
"Primbr","Pro-Bud","Pro-Con","Pro-Eko","Pro-Ex",
"Pro-Instal","Pro Futuro VRT","Problem","Probud","Probudex",
"Probuild","Prochem","Prod-Bud","Prod-Mat-Bud","Profes",
"Profil","Progres Complex-Bud","Proinwest","Promarem","Promen G and B",
"Promet","Promont","Promonta","Promor","Pronad",
"Prosper-Instalbud Eko","Protech","Protel","Protom","Proweld",
"PUI","Raba","Raba II","Radex","Radimex",
"Ragost","Rakop","Rawex","RDI","Rdi-Inwestor",
"Rece Poland","Reformer","Reget","Rem","Rem-Bud I",
"Remal","Remax","Rembor","Rembud","Rembud PBK",
"Remin","Remo-Bud","Remo-Budowa","Remobud","Remontex",
"Remtur","Renoma","Renova","Renowa","Resbud",
"Reter","Rewis","Rexbud","Rinol Polska","Ro-Land",
"Rob-Bud","Robto","Robud","Rokkol","Rolwod",
"Romabud","Romar","Rombud","Rondo","Rurbud",
"Rymtar","S-Bud","S&G","S.R.","Saman-Bud",
"San-Bud","Sanbud","Sawand-Bud","Seba","Sekrabel",
"Set","Siba","Sibud","Siding","Sirbud",
"SKB","Ski-Dom","Skorbud","Sofbud","Solgrud",
"Soli-Bud","Solvex","Sorat Invest","SOS","Sowbud",
"Specker Bud","Spectra","Spui","Stakon","Stalbud",
"Stan","Stanbud","Stand","Star","Star-Bud",
"Steel-Con","Stelco","Stubo","SUB","Supo-Construction",
"Supromar","System","Systembud","Szelbud","Szmyd",
"Tadan","Tam Romabud","Tamur","Tandom","TBI",
"TBS","TCI","Te-Pe","Teampol","Tebodin Poland",
"Technikol","Techno-Bud","Techno Bud","Teeldom","Tehal",
"Tekon","Telbat","Telbud","Telkon","Tepoz",
"Ter-Bud","Teren","Termeko","Termobud","Termoflex",
"Termosystem","Terra","Terra Nova","Thermbud","Tirex",
"Tom-Bud","Tombud","Tomex","Tomico","Top",
"Tractus","Tram","Transbud","Transcem","Tres",
"Trinart","Trio","Tulbud B.E.","Turbud","Tutto",
"Tytan","Ubizo","Ukleina","Uni-Kern","Unibud",
"Unibud Development","Uniimak","Unimirex","Unipol-Projekt","Uniremb",
"Unit","Uniwersbud","Urbex","Vester","Vista",
"W.I.B.","Wabel","Wabet","Wacetob","Wach",
"Wadeco","Wan","Waplex","War Inwest","WDI",
"Weg","Wega","Wega Bis","Wendex","Werda",
"Westprojekt","Wiak Seals","Wiksbud","Wilky","Wima",
"Wimar","Winad","Winpol-Building-Industrial Co.","Witan","Witbud",
"Witka","Wodrol","Woex","Woj-Bud","Wokbud",
"Wolbud","WTM Partner","Wudimex","Zalup","Zambud",
"Zbud","Zep-Inpro","Zetpol","Zibex","Zrelbud 90",
"Zub","Zubil","Zurbud",]

rodzaje=["Agencja Inwestycyjna","Agencja Wspierania Inicjatyw Mieszkaniowych","Architektura Budownictwo Inwestycje","Biuro Budowlane Marketingowo-Konsultingowe","Biuro Handlowe",
"Biuro Inwestorskie","Biuro Inwestycji","Biuro Inwestycyjne","Biuro Konsultingowo-Projektowe","Biuro Obsługi Budownictwa",
"Biuro Obsługi Budowy","Biuro Obsługi Inwestora","Biuro Obsługi Inwestycji","Biuro Obsługi Inwestycyjnej","Biuro Opracowań Kosztorysów",
"Biuro Projektów","Biuro Projektowania Ekspertyz Budowlanych i Wycen","Biuro Projektowo-Inwestycyjne","Biuro Promocji","Biuro Robót Budowlanych",
"Biuro Usług Inżynierskich Pracownia Budowlana","Biuro Usług Inwestycyjnych","Biuro Usług Projektowo-Kosztorysowych","Budowlana Spółdzielnia Pracy","Budownictwo L±dowo-Inżynieryjne",
"Budownictwo Ogólne","Budownictwo Wielobranżowe","Centrum Inwestycji Budowlanych","Centrum Promocyjno-Handlowe","Doradztwo Budowlane",
"Firma Budowlana","Firma Budowlano-Drogowa","Firma Budowlano-Handlowa","Firma Budowlano-Handlowo-Usługowa","Firma Budowlano-Instalacyjna",
"Firma Budowlano-Inwestycyjna","Firma Budowlano-Projektowa","Firma Budowlano-Stolarska","Firma Handlowo-Budowlana","Firma Handlowo-Usługowa",
"Firma Ogólnobudowlana","Firma Produkcyjno-Handlowo-Usługowa","Firma Remontowo-Budowlana","Firma Stolarska","Firma Usług Budowlanych",
"Firma Usługowo-Handlowa","Firma Wielobranżowa","Hurt-Detal","Inwestorsko-Projektowa Spółdzielnia Pracy","Inwestycje Technologiczne",
"Modernizacja Obiektów Sportowych","Obsługa Inwestycji Budowlanych","Obsługa Techniczna Budownictwa","Pracownia Kosztorysowa","Projektowanie Budowlane",
"Przedsiębiorstwo","Przedsiębiorstwo Budowlane","Przedsiębiorstwo Budowlane Biuro","Przedsiębiorstwo Budowlane Biuro Handlowe ","Przedsiębiorstwo Budowlane Handlowo-Usługowe",
"Przedsiębiorstwo Budowlane Import-Eksport","Przedsiębiorstwo Budowlane Instalacyjno-Usługowo-Handlowe","Przedsiębiorstwo Budowlano-Handlowe","Przedsiębiorstwo Budowlano-Instalacyjne","Przedsiębiorstwo Budowlano-Inwestycyjne",
"Przedsiębiorstwo Budowlano-Konsultingowe","Przedsiębiorstwo Budowlano-Melioracyjne","Przedsiębiorstwo Budowlano-Montażowe","Przedsiębiorstwo Budowlano-Produkcyjne","Przedsiębiorstwo Budowlano-Remontowo-Usługowo-Handlowe",
"Przedsiębiorstwo Budowlano-Usługowe","Przedsiębiorstwo Budowlano-Usługowo-Handlowe","Przedsiębiorstwo Budownictwa","Przedsiębiorstwo Budownictwa Kolejowego","Przedsiębiorstwo Budownictwa Ogólnego",
"Przedsiębiorstwo Handlowe","Przedsiębiorstwo Handlowo-Remontowe","Przedsiębiorstwo Handlowo-Usługowe","Przedsiębiorstwo Handlowo-Usługowe Biuro Projektowe","Przedsiębiorstwo Handlowo-Usługowe Inwestycje Budowlane",
"Przedsiębiorstwo Handlowo-Usługowe Systemy Budowlane","Przedsiębiorstwo Handlowo-Usługowo-Produkcyjne","Przedsiębiorstwo Inżynieryjno-Budowlane","Przedsiębiorstwo Instalacji Elektrycznych","Przedsiębiorstwo Instalacyjno-Budowlane",
"Przedsiębiorstwo Instalacyjno-Montażowe","Przedsiębiorstwo Inwestycji","Przedsiębiorstwo Inwestycji Gospodarczej","Przedsiębiorstwo Montażowo-Budowlane","Przedsiębiorstwo Ogólnobudowlane",
"Przedsiębiorstwo Produkcyjno-Budowlane","Przedsiębiorstwo Produkcyjno-Handlowe","Przedsiębiorstwo Produkcyjno-Handlowo-Usługowe","Przedsiębiorstwo Produkcyjno-Usługowe","Przedsiębiorstwo Produkcyjno-Usługowo-Handlowe",
"Przedsiębiorstwo Projektowo-Budowlane","Przedsiębiorstwo Projektowo-Inwestycyjne","Przedsiębiorstwo Realizacji Budownictwa","Przedsiębiorstwo Realizacji Inwestycji","Przedsiębiorstwo Remontowo-Budowlane",
"Przedsiębiorstwo Remontowo-Inwestycyjne","Przedsiębiorstwo Robót Budowlano-Inżynieryjnych","Przedsiębiorstwo Robót Budowlano-Montażowych","Przedsiębiorstwo Robót Budowlanych i Melioracyjnych","Przedsiębiorstwo Robót Inżynieryjno-Budowlanych",
"Przedsiębiorstwo Robót Inżynieryjnych","Przedsiębiorstwo Robót Montażowych","Przedsiębiorstwo Techniczno-Handlowe","Przedsiębiorstwo Techniczno-Usługowe","Przedsiębiorstwo Transportowo-Sprzętowe Budownictwa Oddział",
"Przedsiębiorstwo Usług Budowlanych","Przedsiębiorstwo Usług Inwestycyjnych","Przedsiębiorstwo Usługowe","Przedsiębiorstwo Usługowo-Handlowe","Przedsiębiorstwo Usługowo-Handlowe Inwestycje Budowlane",
"Przedsiębiorstwo Usługowo-Handlowo-Produkcyjne","Przedsiębiorstwo Usługowo-Montażowe","Przedsiębiorstwo Usługowo-Produkcyjne","Przedsiębiorstwo Wielobranżowe","Przedsiębiorstwo Zagraniczne",
"Remontowo-Budowlana Spółdzielnia Pracy","Roboty Podziemne","S.C.","S.C. Agencja Budowlana","S.C. Agencja Usługowa",
"S.C. Biuro","S.C. Biuro Doradcze","S.C. Biuro Inwestycji","S.C. Biuro Inwestycyjne","S.C. Biuro Obsługi Inwestycji",
"S.C. Biuro Technicznej Obsługi Budownictwa","S.C. Biuro Usług Budowlanych","S.C. Biuro Usług Inżyniersko-Budowlanych","S.C. Biuro Usług Inwestycyjnych","S.C. Biuro Usług Techniczno-Organizacyjnych",
"S.C. Budownictwo Inżynieryjne","S.C. Firma Budowlana","S.C. Firma Budowlano-Handlowa","S.C. Firma Handlowa","S.C. Firma Handlowo-Usługowa",
"S.C. Firma Inżynierska","S.C. Firma Inwestycyjno-Budowlana","S.C. Firma Ogólnobudowlana","S.C. Firma Projektowo-Wykonawcza","S.C. Firma Usługowo-Budowlana",
"S.C. Inwestycje Budowlane","S.C. Przedsiębiorstwo Budowlane","S.C. Przedsiębiorstwo Budowlane Handlu i Usług","S.C. Przedsiębiorstwo Budowlane Produkcyjno-Usługowo-Handlowe","S.C. Przedsiębiorstwo Budowlano-Handlowe",
"S.C. Przedsiębiorstwo Budowlano-Montażowe","S.C. Przedsiębiorstwo Budowlano-Produkcyjne","S.C. Przedsiębiorstwo Budowlano-Remontowe","S.C. Przedsiębiorstwo Budowlano-Usługowo-Handlowe","S.C. Przedsiębiorstwo Budownictwa Kolejowego",
"S.C. Przedsiębiorstwo Handlowe","S.C. Przedsiębiorstwo Handlowo-Produkcyjne","S.C. Przedsiębiorstwo Handlowo-Usługowe","S.C. Przedsiębiorstwo Inżynieryjne","S.C. Przedsiębiorstwo Instalacyjno-Budowlane",
"S.C. Przedsiębiorstwo Inwestycji Budowlanych","S.C. Przedsiębiorstwo Inwestycyjne","S.C. Przedsiębiorstwo Inwestycyjno-Budowlane","S.C. Przedsiębiorstwo Kompleksowej Realizacji Budownictwa","S.C. Przedsiębiorstwo Produkcyjno-Budowlane Centrum Budowlane",
"S.C. Przedsiębiorstwo Produkcyjno-Handlowe","S.C. Przedsiębiorstwo Produkcyjno-Handlowo-Usługowe","S.C. Przedsiębiorstwo Produkcyjno-Remontowe","S.C. Przedsiębiorstwo Produkcyjno-Usługowe","S.C. Przedsiębiorstwo Produkcyjno-Usługowo-Handlowe",
"S.C. Przedsiębiorstwo Projektowo-Wykonawcze","S.C. Przedsiębiorstwo Prywatne","S.C. Przedsiębiorstwo Realizacji Inwestycji","S.C. Przedsiębiorstwo Remontowo-Budowlane","S.C. Przedsiębiorstwo Robót Instalacyjno-Budowlanych",
"S.C. Przedsiębiorstwo Usług Budowlanych","S.C. Przedsiębiorstwo Usług Inwestycyjnych","S.C. Przedsiębiorstwo Usługowe","S.C. Przedsiębiorstwo Usługowo-Budowlane","S.C. Przedsiębiorstwo Usługowo-Handlowe",
"S.C. Przedsiębiorstwo Usługowo-Handlowe Import-Eksport","S.C. Przedsiębiorstwo Usługowo-Produkcyjne","S.C. Przedsiębiorstwo Usługowo-Wykonawcze","S.C. Przedsiębiorstwo Wielobranżowe","S.C. Przedsiębiorstwo Wielobranżowe Inwestycje Budowlane",
"S.C. Spółka Budowlano-Usługowa","S.C. Usługi Budowlane","S.C. Wielobranżowe Przedsiębiorstwo Inwestycyjno-Usługowo-Handlowe","S.C. Zakład Budowlano-Instalacyjny","S.C. Zakład Budowlano-Remontowy",
"S.C. Zakład Budowlany","S.C. Zakład Budowlany Wulkanizacja","S.C. Zakład Budownictwa Ogólnego","S.C. Zakład Instalacyjno-Budowlany","S.C. Zakład Inwestycyjny",
"S.C. Zakład Obsługi Inwestycji","S.C. Zakład Obsługi Procesorów Inwestycyjnych","S.C. Zakład Ogólnobudowlany","S.C. Zakład Produkcyjno-Usługowy","S.C. Zakład Realizacji Inwestycji",
"S.C. Zakład Robót Instalacyjno-Budowlanych","S.C. Zakład Techniczny","S.C. Zakład Usług Budowlanych","S.C. Zakład Usług Instalacyjnych","S.C. Zakład Usług Inwestycyjnych",
"S.C. Zakład Usługowo-Produkcyjno-Handlowy","S.C. Zakład Usługowy","S.J.","SA","SA Centrum Usługowo-Handlowe",
"SA Firma Budowlana","SA Firma Inwestycyjno-Budowlana","SA Grupa Kapitałowa ","SA Kierownictwo Zespołu Budów","SA Korporacja",
"SA Oddział","SA Oddział Mostowo-Drogowy","SA Oddział nr 3","SA Przedsiębiorstwo Budowlane","SA Przedsiębiorstwo Budowlano-Usługowe",
"SA Przedsiębiorstwo Budownictwa Ogólnego","SA Przedsiębiorstwo Budownictwa Przemysłowego","SA Przedsiębiorstwo Budownictwa Przemysłowego nr 3","SA Przedsiębiorstwo Budownictwa Przemysłowego Zarz±d","SA Przedsiębiorstwo Budowy Kopalń",
"SA Przedsiębiorstwo Kompleksowej Realizacji Budownictwa","SA Przedsiębiorstwo Produkcyjne","SA Przedsiębiorstwo Produkcyjno-Usługowo-Handlowe","SA Przedsiębiorstwo Robót i Usług Budowlanych","SA Przedsiębiorstwo Robót Inżynieryjnych",
"SA Przedsiębiorstwo Techniczno-Handlowe","SA Przedsiębiorstwo Usług Technicznych","SA Usługi Inwestycyjne","SA Zakład Produkcji Przemysłowej","Sp z o.o. Firma Budowlana",
"Sp. o.o. Przedsiębiorstwo Produkcyjno-Handlowo-Usługowe","Sp. z o.o.","Sp. z o.o. Agencja Gospodarcza","Sp. z o.o. Agencja Inwestycji","Sp. z o.o. Agencja Rozwoju Regionalnego i Inwestycji",
"Sp. z o.o. Biuro Handlowe","Sp. z o.o. Biuro Inżynierskie","Sp. z o.o. Biuro Inżynieryjno-Techniczne","Sp. z o.o. Biuro Inwestycyjne","Sp. z o.o. Biuro Obsługi Inwestycji",
"Sp. z o.o. Biuro Prawno-Inwestycyjne","Sp. z o.o. Biuro Regionalne","Sp. z o.o. Biuro Techniczne","Sp. z o.o. Budowlane Inwestycje","Sp. z o.o. Budownictwo",
"Sp. z o.o. Elementy Budowlane","Sp. z o.o. Energetyka Poznańska Zakład Inwestycji Energetycznych","Sp. z o.o. Firma","Sp. z o.o. Firma Budowlana","Sp. z o.o. Firma Budowlano-Handlowo-Usługowa",
"Sp. z o.o. Firma Inwestycyjno-Budowlana","Sp. z o.o. Firma Montażowo-Remontowa","Sp. z o.o. Firma Projektowo-Konsultingowa","Sp. z o.o. Grupa Inwestycji Budowlanych","Sp. z o.o. Grupa Inwestycyjna",
"Sp. z o.o. Inwestycje Budowlane","Sp. z o.o. Inwestycyjno-Remontowa","Sp. z o.o. Korporacja Budowlano-Handlowa","Sp. z o.o. Korporacja Firm Budowlanych","Sp. z o.o. O¶rodek Wdrożeń Ekonomiczno-Organizacyjnych Budownictwa",
"Sp. z o.o. Obsługa Inwestycji","Sp. z o.o. Przedsiębiorstwo","Sp. z o.o. Przedsiębiorstwo Budowlane","Sp. z o.o. Przedsiębiorstwo Budowlane Biuro Handlowe","Sp. z o.o. Przedsiębiorstwo Budowlane Hurtownia",
"Sp. z o.o. Przedsiębiorstwo Budowlano-Handlowe","Sp. z o.o. Przedsiębiorstwo Budowlano-Handlowo-Usługowe","Sp. z o.o. Przedsiębiorstwo Budowlano-Inżynieryjne","Sp. z o.o. Przedsiębiorstwo Budowlano-Instalacyjne","Sp. z o.o. Przedsiębiorstwo Budowlano-Inwestycyjne",
"Sp. z o.o. Przedsiębiorstwo Budowlano-Montażowe","Sp. z o.o. Przedsiębiorstwo Budowlano-Produkcyjne","Sp. z o.o. Przedsiębiorstwo Budowlano-Projektowe","Sp. z o.o. Przedsiębiorstwo Budowlano-Telekomunikacyjne","Sp. z o.o. Przedsiębiorstwo Budowlano-Usługowe",
"Sp. z o.o. Przedsiębiorstwo Budowlano-Usługowo-Handlowe","Sp. z o.o. Przedsiębiorstwo Budowlano-Usługowo-Produkcyjne","Sp. z o.o. Przedsiębiorstwo Budownictwa","Sp. z o.o. Przedsiębiorstwo Budownictwa Inżynieryjnego","Sp. z o.o. Przedsiębiorstwo Budownictwa Ogólnego",
"Sp. z o.o. Przedsiębiorstwo Budownictwa Przemysłowego","Sp. z o.o. Przedsiębiorstwo Budowy Domów","Sp. z o.o. Przedsiębiorstwo Budowy Obiektów Użyteczno¶ci Publicznej","Sp. z o.o. Przedsiębiorstwo Dewelopersko-Budowlane","Sp. z o.o. Przedsiębiorstwo Doradztwa Inwestycyjnego",
"Sp. z o.o. Przedsiębiorstwo Handlowo-Usługowe","Sp. z o.o. Przedsiębiorstwo Handlowo-Usługowo-Budowlane","Sp. z o.o. Przedsiębiorstwo Handlowo-Usługowo-Produkcyjne","Sp. z o.o. Przedsiębiorstwo Inżynierskie","Sp. z o.o. Przedsiębiorstwo Inżynieryjno-Budowlane",
"Sp. z o.o. Przedsiębiorstwo Inżynieryjno-Geodezyjne","Sp. z o.o. Przedsiębiorstwo Innowacji Budowlanych","Sp. z o.o. Przedsiębiorstwo Innowacyjno-Produkcyjne","Sp. z o.o. Przedsiębiorstwo Innowacyjno-Wdrożeniowe Budownictwa","Sp. z o.o. Przedsiębiorstwo Instalacyjno-Montażowe",
"Sp. z o.o. Przedsiębiorstwo Inwestycji Budowlanych","Sp. z o.o. Przedsiębiorstwo Inwestycyjne","Sp. z o.o. Przedsiębiorstwo Inwestycyjno-Budowlane","Sp. z o.o. Przedsiębiorstwo Inwestycyjno-Projektowe","Sp. z o.o. Przedsiębiorstwo Inwestycyjnych Usług Inżynierskich",
"Sp. z o.o. Przedsiębiorstwo Konsultingowo-Usługowe Gospodarki Wodno-ściekowej i Ochrony środowiska","Sp. z o.o. Przedsiębiorstwo Modernizacji Zakładów Przemysłowych i Urządzeń Ochrony środowiska","Sp. z o.o. Przedsiębiorstwo Montażowo-Budowlane","Sp. z o.o. Przedsiębiorstwo Obsługi Budownictwa","Sp. z o.o. Przedsiębiorstwo Obsługi Inwestycji",
"Sp. z o.o. Przedsiębiorstwo Obsługi Inwestycyji","Sp. z o.o. Przedsiębiorstwo Ogólnobudowlane","Sp. z o.o. Przedsiębiorstwo Produkcji i Usług Budowlanych","Sp. z o.o. Przedsiębiorstwo Produkcyjno-Budowlane","Sp. z o.o. Przedsiębiorstwo Produkcyjno-Handlowe",
"Sp. z o.o. Przedsiębiorstwo Produkcyjno-Handlowe Firma Budowlana","Sp. z o.o. Przedsiębiorstwo Produkcyjno-Handlowo-Usługowe","Sp. z o.o. Przedsiębiorstwo Produkcyjno-Handlowo-Usługowe Biuro Handlowe","Sp. z o.o. Przedsiębiorstwo Produkcyjno-Handlowo-Usługowe Biuro Inwestycji Budowlanych","Sp. z o.o. Przedsiębiorstwo Produkcyjno-Handlowo-Usługowe Usługi Ogólnobudowlane",
"Sp. z o.o. Przedsiębiorstwo Produkcyjno-Usługowe","Sp. z o.o. Przedsiębiorstwo Produkcyjno-Usługowo-H","Sp. z o.o. Przedsiębiorstwo Produkcyjno-Usługowo-Handlowe","Sp. z o.o. Przedsiębiorstwo Produkcyjno-Usługowo-Handlowe Zakład Budowlany","Sp. z o.o. Przedsiębiorstwo Projektowo-Budowlane",
"Sp. z o.o. Przedsiębiorstwo Przygotowania i Realizacji Inwestycji","Sp. z o.o. Przedsiębiorstwo Realizacji Budownictwa","Sp. z o.o. Przedsiębiorstwo Realizacji Budownictwa Mieszkaniowego","Sp. z o.o. Przedsiębiorstwo Realizacji Inwestycji","Sp. z o.o. Przedsiębiorstwo Remontów i Budownictwa Ogólnego Biuro Handlowe",
"Sp. z o.o. Przedsiębiorstwo Remontowe","Sp. z o.o. Przedsiębiorstwo Remontowo-Budowlane","Sp. z o.o. Przedsiębiorstwo Remontowo-Montażowe","Sp. z o.o. Przedsiębiorstwo Robót Inżynieryjno-Montażowych","Sp. z o.o. Przedsiębiorstwo Robót Instalacyjno-Montażowych",
"Sp. z o.o. Przedsiębiorstwo Robót Wysokościowych","Sp. z o.o. Przedsiębiorstwo Rozbudowy Infrastruktury Miejskiej","Sp. z o.o. Przedsiębiorstwo Usług Budowlano-Inwestycyjnych","Sp. z o.o. Przedsiębiorstwo Usług Budowlanych","Sp. z o.o. Przedsiębiorstwo Usług Inwestycyjnych",
"Sp. z o.o. Przedsiębiorstwo Usług Inwestycyjnych Filia","Sp. z o.o. Przedsiębiorstwo Usług Konsultingowych","Sp. z o.o. Przedsiębiorstwo Usług Technicznych","Sp. z o.o. Przedsiębiorstwo Usługowo-Budowlane","Sp. z o.o. Przedsiębiorstwo Usługowo-Budowlano-Handlowe",
"Sp. z o.o. Przedsiębiorstwo Usługowo-Handlowe","Sp. z o.o. Przedsiębiorstwo Usługowo-Inwestycyjne","Sp. z o.o. Przedsiębiorstwo Usługowo-Inwestycyjne Budownictwa i Energetyki","Sp. z o.o. Przedsiębiorstwo Usługowo-Produkcyjne","Sp. z o.o. Przedsiębiorstwo Usługowo-Produkcyjno-Handlowe",
"Sp. z o.o. Przedsiębiorstwo Usługowo-Wytwórcze","Sp. z o.o. Przedsiębiorstwo Wielobranżowe","Sp. z o.o. Przedsiębiorstwo Wielobranżowe Usług Inwestycyjnych","Sp. z o.o. Przedsiębiorstwo Wielobranżowe Zakład Pracy Chronionej","Sp. z o.o. Przedsiębiorstwo Zagospodarowania Miast i Osiedli",
"Sp. z o.o. Przedsiębiorstwo Zagraniczne","Sp. z o.o. Regionalne Towarzystwo Budownictwa Społecznego","Sp. z o.o. Rejonowe Przedsiębiorstwo Inwestycyjno-Handlowo-Usługowe","Sp. z o.o. Spółka Inwestycyjno-Budowlana","Sp. z o.o. Towarzystwo Budowlane",
"Sp. z o.o. Towarzystwo Budownictwa Społecznego","Sp. z o.o. Towarzystwo Inwestycyjne","Sp. z o.o. Usługi Budowlane","Sp. z o.o. Wielobranżowe Przedsiębiorstwo","Sp. z o.o. Wielobranżowe Przedsiębiorstwo Budowlano-Produkcyjne",
"Sp. z o.o. Wielobranżowe Przedsiębiorstwo Inwestycyjne","Sp. z o.o. Wielobranżowe Przedsiębiorstwo Remontowo-Budowlane","Sp. z o.o. Zakład Budowlano-Instalacyjny","Sp. z o.o. Zakład Budowlano-Montażowy","Sp. z o.o. Zakład Budowlany",
"Sp. z o.o. Zakład Energetyczny Centrum Projektowania i Realizacji Inwestycji","Sp. z o.o. Zakład Inwestycji Budowlanych","Sp. z o.o. Zakład Inwestycji Mieszkaniowych","Sp. z o.o. Zakład Montażowo-Produkcyjny ","Sp. z o.o. Zakład Produkcyjno-Usługowo-Handlowy",
"Sp. z o.o. Zakład Produkcyjno-Usługowy","Sp. z o.o. Zakład Produkcyjny","Sp. z o.o. Zakład Projektowo-Wdrożeniowy","Sp. z o.o. Zakład Przygotowania Inwestycji","Sp. z o.o. Zakład Realizacji Inwestycji",
"Sp. z o.o. Zakład Robót Inżynieryjno-Budowlanych","Sp. z o.o. Zakład Robót Ogólnobudowlanych","Sp. z o.o. Zakład Usług Budowlanych","Sp. z o.o. Zakład Usług Inwestycyjnych","Sp. z o.o. Zakład Usług Technicznych",
"Sp. z o.o. Zakład Usługowo-Produkcyjny","Sp. z o.o. Zespół Innowacyjno-Wdrożeniowy","Sp. z o.o. Zielona Góra Kierownictwo Grupy Robót nr 2","Sp.z o.o. Przedsiębiorstwo Budowlane Produkcyjno-Usługowo-Handlowe","Spółdzielcze Przedsiębiorstwo Budowlano-Usługowe",
"Spółdzielnia Budowlana","Spółdzielnia Budowlano-Mieszkaniowa","Spółdzielnia Inwestycji Mieszkaniowych","Spółdzielnia Mieszkaniowa","Spółdzielnia Pracy",
"Spółdzielnia Pracy Usług Inwestycyjnych","Spółdzielnia Produkcyjno-Usługowa","Spółdzielnia Rzemieślnicza","Spółdzielnia Rzemieślnicza Budowlano-Metalowa Usługi Budowlane","Spółdzielnia Rzemieślnicza Inwestycje Budowlane",
"Spółdzielnia Usług Budowlane","Spółdzielnia Usług Inwestycyjnych","Spółdzielnia Wielobranżowa","Towarzystwo Inwestycyjne","Usługi Budowlane",
"Usługi Budowlano-Inwestycyjne","Usługi Inwestorskie","Usługi Inwestycyjne","Usługi Ogólnobudowlane","Usługi Projektowo-Budowlane",
"Usługi Remontowo-Budowlane","Zakład Budowlano-Handlowy","Zakład Budowlano-Instalacyjny","Zakład Budowlano-Montażowy","Zakład Budowlano-Produkcyjno-Handlowy",
"Zakład Budowlano-Produkcyjny","Zakład Budowlano-Remontowy","Zakład Budowlany","Zakład Budownictwa Ogólnego","Zakład Ciesielski Usługi Budowlane",
"Zakład Handlowo-Usługowy","Zakład Inwestycji Budownictwa","Zakład Inwestycyjno-Budowlany","Zakład Montażowo-Sprzętowy","Zakład Obsługi Budownictwa",
"Zakład Obsługi Inwestycji","Zakład Ogólnobudowlany","Zakład Produkcyjno-Handlowo-Usługowy","Zakład Produkcyjno-Handlowy","Zakład Produkcyjno-Usługowo-Handlowy",
"Zakład Produkcyjno-Usługowy Biuro Techniczne","Zakład Produkcyjny","Zakład Projektowo-Wykonawczy","Zakład Remontowo-Budowlany","Zakład Remontowo-Budowlany Usługowo-Handlowy",
"Zakład Robót Budowlanych","Zakład Robót Inżynieryjno-Budowlanych","Zakład Usług Budowlanych","Zakład Usług Inwestycyjnych","Zakład Usług Inwestycyjnych Firma Budowlana",
"Zakład Usług Remontowo-Budowlanych","Zakład Usługowo-Handlowy","Zakład Usługowy","Zakład Wielobranżowy","Zakłady Projektowo-Budowlane",
]

class DaneFirm:
   def __init__(self):
      self.Nazwy=nazwy
      self.Rodzaje=rodzaje
   def __getattr__(self,name):
      if name=='Nazwa':
         return self.GetNazwa()
      if name=='Rodzaj':
         return self.GetRodzaj()
      if name=='Firma':
         return self.GetNazwa()+' '+self.GetRodzaj()
   def GetNazwa(self):
      return self.Nazwy[random.randint(0,len(self.Nazwy)-1)]
   def GetRodzaj(self):
      return self.Rodzaje[random.randint(0,len(self.Rodzaje)-1)]



